# 1. What is a Dataset?

## Definition

A dataset is a collection of related data organized into rows and columns. It contains information about objects, events, people, products, or transactions.

Each row represents an individual record, and each column represents a particular attribute or variable.

## Why Is a Dataset Important?

Datasets are the foundation of Data Analysis and Machine Learning. They help us understand information, identify patterns, discover trends, and make data-driven decisions.

Before performing data preprocessing or building a Machine Learning model, we must understand the dataset's structure, features, data types, and quality.

## Basic Components of a Dataset

- **Rows:** Represent individual records or observations.
- **Columns:** Represent attributes or variables.
- **Features:** Describe the properties of each record.
- **Values:** Represent the actual information stored in the dataset.

## Conclusion

Understanding a dataset is the first step in Exploratory Data Analysis (EDA). It helps us determine what information is available and whether the data is suitable for further analysis or Machine Learning.

# Step 2 – Demonstrate the Concept

## 1. Simple Example

Consider the following student dataset:

| Student_ID | Name | Age | Marks |
|---|---|---:|---:|
| 101 | Arun | 20 | 85 |
| 102 | Priya | 21 | 90 |
| 103 | Ravi | 20 | 72 |

This table is a dataset because it contains related information organized into rows and columns.

- Each row represents one student.
- Each column represents an attribute of a student.
- Each cell contains a specific value.

## 2. Real-World Example

An online shopping website collects information about customer orders, including product details, quantities, prices, order dates, and customer locations.

These records form a dataset that can be analyzed to understand customer purchasing behavior.

## 3. Business Example

An e-commerce company analyzes its sales dataset to identify best-selling products, understand customer preferences, compare monthly revenue, and improve business decisions.

## 4. AI/ML Use Case

A Machine Learning Engineer can analyze historical customer transaction data to identify purchasing patterns and develop customer segmentation models.

The model can group customers based on their purchasing behavior, helping businesses create more relevant marketing strategies.

## 5. Importance in Data Analysis

Understanding a dataset helps us identify available information, recognize different data types, detect data-quality problems, and select suitable analysis techniques.

It also helps us determine whether the dataset is appropriate for the intended Machine Learning task.

In [2]:
import os

print("Current working directory:", os.getcwd())
print("\nFiles available in this folder:")
print(os.listdir())

Current working directory: C:\Sprint 4 – Data Inspection & Exploratory Data Analysis (EDA)

Files available in this folder:
['.ipynb_checkpoints', '01_Dataset_Understanding.ipynb.ipynb']

In [4]:

import pandas as pd
import numpy as np

# Load the Online Retail II dataset
file_path = "online_retail_II.xlsx"

df = pd.read_excel(
    file_path,
    sheet_name="Year 2009-2010"
)

# Display the first five records
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

# Code Explanation and Output Interpretation

## What Does the Code Do?

The code loads the Online Retail II Excel dataset into a Pandas DataFrame and displays the first five records.

## Why Is This Method Used?

`pd.read_excel()` is used because the dataset is stored in an Excel file. `df.head()` provides a quick preview of the records without displaying the entire dataset.

## What Does the Output Mean?

The output shows sample retail transactions containing invoice details, product information, quantities, prices, dates, customer identifiers, and country information.

Each row represents a product line associated with an invoice.

## What Insights Can Be Obtained?

The preview helps us understand the available information and identify the initial data types. It also helps us notice values that may require further investigation, such as missing descriptions or unusual quantities.

## How Can This Affect an ML Pipeline?

Understanding the dataset helps us identify potential features, distinguish identifiers from useful measurements, and plan data-quality checks before preprocessing and model development.

# Topic 2: What is a Feature?

## Definition

A feature is an individual attribute or variable that describes a record in a dataset. In a tabular dataset, features are usually represented by columns.

Features provide information about the records and help us understand the characteristics of the data.

## Why Are Features Important?

Features help us explore relationships, identify patterns, compare records, and understand the factors that may influence an outcome.

In Machine Learning, selected features are used as input variables to train a model and generate predictions.

## Examples of Features

In an e-commerce dataset:

- `Quantity` represents the number of units purchased.
- `Price` represents the price per unit.
- `Country` identifies the customer's country.
- `Description` provides the product description.

## Feature Selection Consideration

Not every column should automatically be used as a Machine Learning input. Identifier columns, irrelevant information, and data leakage risks must be evaluated before selecting features.

## Conclusion

Understanding features is an important part of Exploratory Data Analysis because it helps us identify useful information and prepare appropriate inputs for further analysis and Machine Learning.

# Step 2: Demonstrate the Concept

## 1. Simple Example

Consider the following student dataset:

| Student_ID | Age | Study_Hours | Marks |
|---|---:|---:|---:|
| 101 | 20 | 3 | 75 |
| 102 | 21 | 5 | 88 |
| 103 | 20 | 2 | 65 |

Here, `Age`, `Study_Hours`, and `Marks` are features describing each student. If the objective is to predict marks, `Age` and `Study_Hours` may be input features, while `Marks` is the target variable.

## 2. Real-World Example

An online shopping platform records product prices, quantities, customer locations, and product descriptions. These features help describe customer transactions.

## 3. Business Example

A retail company analyzes product prices, quantities sold, and customer locations to understand sales performance and purchasing patterns.

## 4. AI/ML Use Case

A Machine Learning Engineer may use transaction quantity, unit price, and other relevant customer or product attributes to develop a model that predicts customer purchasing behavior.

The usefulness of each feature depends on the prediction objective and the quality of the available data.

## 5. Importance in Data Analysis

Understanding features helps us identify column meanings, compare numerical and categorical information, detect irrelevant attributes, and select suitable analysis methods.

It also helps us choose appropriate input variables before training a Machine Learning model.

In [5]:

# Display all feature names (column names)
print("Dataset Features:")
print(df.columns.tolist())

# Display the first five records
print("\nFirst Five Records:")
display(df.head())

Dataset Features:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

First Five Records:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

# Step 3: Code Explanation and Output Interpretation

## Code Explanation

### `df.columns`

This property returns the names of all columns in the DataFrame.

**Why is it used?**

It helps us understand which attributes are available for analysis without displaying the entire dataset.

### `df.columns.tolist()`

This converts the column index into a standard Python list.

**Why is it used?**

A list makes the column names easier to display, review, and use in later Python operations.

### `print("Dataset Features:")`

This prints a heading so the output is easy to understand.

### `display(df.head())`

The `head()` method returns the first five rows by default, and `display()` presents them as a formatted table in Jupyter Notebook.

**Why is it used?**

A small preview helps us connect the column names with their actual values and understand the dataset structure.

## 2. What Does the Output Mean?

The first output lists the dataset's column names, such as `Invoice`, `StockCode`, `Description`, `Quantity`, `InvoiceDate`, `Price`, `Customer ID`, and `Country`.

The table below it shows example values stored in those columns.

Each column describes some aspect of a transaction or product line.

## 3. What Insights Can Be Obtained?

- `Quantity` and `Price` provide numerical information.
- `Description` and `Country` provide descriptive or categorical information.
- `InvoiceDate` provides transaction timing information.
- `Invoice`, `StockCode`, and `Customer ID` act as identifiers and need careful consideration before being used as model inputs.

The appropriate feature types and roles should be confirmed through further inspection.

## 4. How Does This Affect an ML Pipeline?

Feature understanding helps us decide which variables may be useful inputs for a Machine Learning model.

It also helps us identify columns that require transformation, columns that may be irrelevant, and identifiers that should not automatically be treated as meaningful numerical features.

The final feature selection depends on the prediction objective, data quality, and risk of data leakage.

# Topic 3: What is a Target?

## Definition

A target is the outcome or value that a Machine Learning model is designed to predict. It is also called the target variable, dependent variable, or output variable.

The target depends on the problem we want to solve. A dataset may already contain a suitable target, or we may need to define an appropriate outcome based on the business objective.

## Why Is a Target Important?

The target defines what a supervised Machine Learning model should learn to predict. It helps us identify the input features and evaluate whether the model's predictions are accurate.

## Examples of Target Variables

- Student performance prediction: `Marks`
- House price prediction: `House_Price`
- Customer churn prediction: `Churn_Status`
- Sales prediction: `Sales_Amount`

## Target in Exploratory Data Analysis

During EDA, we inspect the target's data type, distribution, missing values, and relationship with other features when a target is available.

For the Online Retail II dataset, there is no predefined target variable. The target must depend on the business problem we choose to investigate.

## Conclusion

Understanding the target is essential before building a supervised Machine Learning model because it determines the prediction objective and guides feature selection, data preparation, and model evaluation.

# Step 2: Demonstrate the Concept

## 1. Simple Example

Consider the following student dataset:

| Age | Study_Hours | Marks |
|---:|---:|---:|
| 20 | 3 | 75 |
| 21 | 5 | 88 |
| 20 | 2 | 65 |

Suppose our objective is to predict students' marks based on their age and study hours.

- Input features: `Age`, `Study_Hours`
- Target variable: `Marks`

The model learns patterns from the input features and corresponding marks.

## 2. Real-World Example

A house-price prediction system uses information such as house size, location, and number of bedrooms to predict the selling price.

In this case, the selling price is the target variable.

## 3. Business Example

An e-commerce company wants to estimate the sales amount for future transactions. It identifies the sales amount as the target and selects relevant historical information as input features.

The prediction can help the company plan inventory and sales strategies.

## 4. AI/ML Use Case

In supervised Machine Learning, the model learns from examples containing input features and known target values.

Regression models predict numerical targets, such as prices or sales amounts. Classification models predict categories, such as whether a customer will churn.

## 5. Importance in Data Analysis

Identifying the target helps us define the business problem, determine which features may be relevant, understand the target distribution, and select an appropriate evaluation metric.

A target should not be chosen arbitrarily. It must represent the outcome we actually want to predict.

In [6]:

import pandas as pd

# Create a small example dataset
student_data = pd.DataFrame({
    "Age": [20, 21, 20],
    "Study_Hours": [3, 5, 2],
    "Marks": [75, 88, 65]
})

# Separate input features and target
X = student_data[["Age", "Study_Hours"]]
y = student_data["Marks"]

print("Input Features (X):")
display(X)

print("Target Variable (y):")
display(y)

# Inspect the retail dataset columns
print("Online Retail II Columns:")
print(df.columns.tolist())

Input Features (X):

   Age  Study_Hours
0   20            3
1   21            5
2   20            2

Target Variable (y):

0    75
1    88
2    65
Name: Marks, dtype: int64

Online Retail II Columns:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

# Step 3: Code Explanation and Output Interpretation

## 1. What Does the Code Do?

The code creates a small student dataset, separates its input features from its target variable, and displays both parts. It then lists the columns available in the Online Retail II dataset.

## 2. Why Is Each Method Used?

### `pd.DataFrame()`

Creates a structured table from the supplied data. It is useful for demonstrating how features and targets are organized.

### `student_data[["Age", "Study_Hours"]]`

Selects two columns as the model inputs. These columns provide information that may help predict student marks.

### `student_data["Marks"]`

Selects the outcome we want to predict. In this example, marks are the target variable.

### `display()`

Displays the selected data in a readable table or Series format in Jupyter Notebook.

### `df.columns.tolist()`

Lists the real retail dataset's column names so we can inspect its available variables.

## 3. What Does the Output Mean?

The input features contain `Age` and `Study_Hours`, while the target contains `Marks`.

Each input row corresponds to the target value in the same row. This relationship is what a supervised learning model uses during training.

The final output lists the Online Retail II columns. These columns describe transactions and products, but none is explicitly designated as the target in the original dataset.

## 4. What Insights Can Be Obtained?

The student example demonstrates how to separate model inputs from the outcome to predict.

For Online Retail II, the available columns alone do not determine the prediction objective. We must first define a business question before selecting or creating a target.

For example, transaction-level sales amount could be derived from quantity multiplied by unit price, but using it as a target would require a clearly defined sales-prediction task.

## 5. How Can This Affect an ML Pipeline?

The target determines the learning objective, the feature-selection process, and the evaluation metric.

If the target is incorrectly defined, the model may solve the wrong problem. If the target information accidentally leaks into the input features, evaluation results may be misleading.

Before training a model, we must define the target, verify its quality, and ensure that input features are appropriate for the prediction task.

# Topic 4: Independent Variables

## Definition

Independent variables are input variables used to explain or predict an outcome. In a dataset, they are often represented by features selected for analysis or model training.

In Machine Learning, independent variables are commonly represented by `X`.

## Why Are Independent Variables Important?

Independent variables provide information that a model uses to identify patterns and make predictions. Selecting suitable input variables helps us build models that address the intended problem.

## Examples

- Student marks prediction: `Study_Hours` and `Age`
- House price prediction: `House_Size` and `Number_of_Bedrooms`
- Sales prediction: relevant product, price, and historical transaction information

## Independent Variables in EDA

During Exploratory Data Analysis, we inspect independent variables to understand their data types, distributions, missing values, unusual values, and relationships with other variables.

## Important Consideration

A variable used as an input should be available at the time of prediction. We must also avoid data leakage, where information unavailable at prediction time or information derived from the target improperly enters the input features.

## Conclusion

Independent variables are the inputs that help explain or predict an outcome. Understanding them helps us select appropriate features and prepare reliable inputs for Machine Learning.

# Step 2: Demonstrate the Concept

## 1. Simple Example

Consider the following student dataset:

| Age | Study_Hours | Marks |
|---:|---:|---:|
| 20 | 3 | 75 |
| 21 | 5 | 88 |
| 20 | 2 | 65 |

If the objective is to predict marks:

- Independent variables: `Age`, `Study_Hours`
- Dependent variable: `Marks`

The input variables provide information that may help the model predict the student's marks.

## 2. Real-World Example

A house-price analysis may use house size, location, and the number of bedrooms as independent variables to estimate a property's selling price.

## 3. Business Example

A retail company wants to estimate future product sales. It may analyze historical prices, promotions, product categories, and past sales information as potential independent variables.

The selected inputs should be available when the prediction is made.

## 4. AI/ML Use Case

A regression model can learn relationships between independent variables and a numerical target. A classification model can use independent variables to predict a category, such as customer churn status.

The usefulness of each input depends on the business objective and the quality of the data.

## 5. Importance in Data Analysis

Inspecting independent variables helps us identify useful inputs, detect missing or unusual values, understand relationships between features, and decide which transformations may be needed before model training.

In [7]:

import pandas as pd

# Create a sample student dataset
student_data = pd.DataFrame({
    "Age": [20, 21, 20, 22, 19],
    "Study_Hours": [3, 5, 2, 6, 4],
    "Marks": [75, 88, 65, 92, 80]
})

# Select independent variables
X = student_data[["Age", "Study_Hours"]]

# Display the independent variables
print("Independent Variables:")
display(X)

# Display the number of input features
print("Number of Independent Variables:", X.shape[1])

# Display the number of records
print("Number of Records:", X.shape[0])

Independent Variables:

   Age  Study_Hours
0   20            3
1   21            5
2   20            2
3   22            6
4   19            4

Number of Independent Variables: 2
Number of Records: 5

# Step 3: Code Explanation and Output Interpretation

## 1. What Does the Code Do?

The code creates a sample student dataset and selects `Age` and `Study_Hours` as independent variables. It then displays the selected inputs and counts the number of records and input features.

## 2. Why Is Each Method Used?

### `pd.DataFrame()`

Creates a tabular dataset from the supplied values. Each dictionary key becomes a column, and each list provides the values for that column.

### `student_data[["Age", "Study_Hours"]]`

Selects only the columns intended to be used as inputs. Double square brackets return a DataFrame containing both columns.

### `X.shape[1]`

The `shape` attribute returns a tuple containing the number of rows and columns. Index `[1]` selects the number of columns, which represents the number of selected input features.

### `X.shape[0]`

Index `[0]` selects the number of rows, which represents the number of records.

### `display(X)`

Shows the selected independent variables in a readable table format in Jupyter Notebook.

## 3. What Does the Output Mean?

The displayed table contains five student records and two input features: `Age` and `Study_Hours`.

The number of independent variables is `2`, and the number of records is `5`.

The `Marks` column is not included in `X` because it represents the outcome we want to predict in this example.

## 4. What Insights Can Be Obtained?

We can confirm that the input dataset contains the two intended variables and that the selected columns have the same number of records.

However, this small example does not prove that age or study hours causes higher marks. More data and suitable analysis would be needed to investigate their relationships.

## 5. How Can This Affect an ML Pipeline?

Independent variables form the input matrix used during model training and prediction.

Correct feature selection helps prevent unrelated columns from entering the model. We must also check data quality, feature relationships, and data leakage before using the inputs for training.

The selected features should match the prediction objective and be available when the model is expected to make predictions.

# Topic 5: Dependent Variables

## Definition

A dependent variable is the outcome that we want to explain, estimate, or predict using other variables. In supervised Machine Learning, it is commonly called the target variable and represented by `y`.

The dependent variable is selected according to the problem we want to solve.

## Why Is a Dependent Variable Important?

The dependent variable defines the outcome of interest. It helps us determine which input features to investigate and what the model should learn to predict.

## Examples

- Student performance prediction: `Marks`
- House price prediction: `House_Price`
- Customer churn prediction: `Churn_Status`
- Sales prediction: `Sales_Amount`

## Dependent Variables in EDA

When a target is available, EDA helps us inspect its data type, distribution, missing values, unusual values, and relationships with potential input features.

## Important Consideration

A dependent variable does not automatically exist as a predefined target in every dataset. In an unsupervised learning task, such as customer segmentation, a predefined target may not be required.

## Conclusion

Understanding the dependent variable helps us define the analytical objective and prepare for suitable feature selection, model training, and evaluation.

# Step 2: Demonstrate the Concept

## 1. Simple Example

Consider this student dataset:

| Age | Study_Hours | Marks |
|---:|---:|---:|
| 20 | 3 | 75 |
| 21 | 5 | 88 |
| 20 | 2 | 65 |

If we want to predict student marks:

- Independent variables: `Age` and `Study_Hours`
- Dependent variable: `Marks`

Marks are the outcome we want to predict.

## 2. Real-World Example

A house-price prediction system estimates a house's selling price using information such as location, size, and number of bedrooms.

The selling price is the dependent variable.

## 3. Business Example

A retail company wants to estimate sales revenue for future periods. It defines the sales amount as the outcome and investigates relevant historical sales, product, and pricing information.

The prediction can support inventory planning and business decisions.

## 4. AI/ML Use Case

In supervised Machine Learning, a model learns from input features paired with known target values.

- Regression predicts numerical outcomes, such as prices or sales amounts.
- Classification predicts categories, such as churn or no churn.

## 5. Importance in Data Analysis

Identifying the dependent variable helps us understand the problem, analyze the outcome's distribution, choose relevant inputs, and select an appropriate evaluation metric.

The target must represent the actual outcome of interest and should be defined before model development.

In [8]:

import pandas as pd

# Create a sample student dataset
student_data = pd.DataFrame({
    "Age": [20, 21, 20, 22, 19],
    "Study_Hours": [3, 5, 2, 6, 4],
    "Marks": [75, 88, 65, 92, 80]
})

# Select the dependent variable
y = student_data["Marks"]

# Display the dependent variable
print("Dependent Variable (Target):")
display(y)

# Check the target data type
print("Target Data Type:", y.dtype)

# Check the number of target values
print("Number of Target Values:", y.shape[0])

Dependent Variable (Target):

0    75
1    88
2    65
3    92
4    80
Name: Marks, dtype: int64

Target Data Type: int64
Number of Target Values: 5

# Step 3: Code Explanation and Output Interpretation

## 1. What Does the Code Do?

The code creates a sample student dataset, selects `Marks` as the dependent variable, displays its values, checks its data type, and counts the number of target values.

## 2. Why Is Each Method Used?

### `pd.DataFrame()`

Creates a structured table from the supplied student information. It allows us to demonstrate how an outcome is stored alongside input features.

### `student_data["Marks"]`

Selects the `Marks` column as the dependent variable. Single square brackets return a Pandas Series containing the selected column's values.

### `display(y)`

Displays the target values in a readable format. This helps us verify that the correct column has been selected.

### `y.dtype`

Returns the data type of the target values. This helps us determine whether the target is stored as integers, floating-point numbers, or another type.

### `y.shape[0]`

Returns the number of values in the target Series. In this example, there are five student records and five corresponding target values.

## 3. What Does the Output Mean?

The target output contains the marks `75`, `88`, `65`, `92`, and `80`.

The data type is expected to be an integer type because all the sample marks are whole numbers. The number of target values is `5`.

Each target value corresponds to the student record in the same row of the original dataset.

## 4. What Insights Can Be Obtained?

The output confirms that `Marks` is the selected outcome and that it contains five values.

The target values can later be analyzed to understand their distribution and relationship with input features. However, this small example alone is not enough to establish a reliable predictive relationship.

## 5. How Can This Affect an ML Pipeline?

The dependent variable defines what a supervised Machine Learning model learns to predict.

Its type influences the choice of model and evaluation metric. For example, predicting numerical marks is a regression task, whereas predicting a category such as pass or fail is a classification task.

Before training, we must check for missing or invalid target values, confirm that the target matches the business objective, and ensure that target information does not leak into the input features.

# Topic 6: Numerical Features

## Definition

Numerical features are variables that represent measurable quantities or counts using numbers. They can be analyzed using mathematical and statistical operations.

Examples include age, quantity, price, salary, distance, and temperature.

## Why Are Numerical Features Important?

Numerical features help us calculate totals, averages, ranges, variations, and relationships between variables. They are useful for identifying patterns and unusual values during Exploratory Data Analysis.

## Types of Numerical Features

- **Discrete Features:** Represent countable values, such as the number of products purchased.
- **Continuous Features:** Represent measurements that can take decimal values within a range, such as weight, height, or temperature.

## Examples in Online Retail II

- `Quantity`: Number of product units in a transaction.
- `Price`: Price per unit.
- `Customer ID`: A numeric-looking identifier, not a direct measurement.

## Numerical Features in Machine Learning

Numerical features can be used as model inputs after checking their meanings, data types, and quality. Some models also require numerical features to be scaled or transformed.

## Conclusion

Identifying numerical features helps us select appropriate statistical methods, inspect data distributions, detect unusual values, and prepare data for further analysis or Machine Learning.

# Step 2: Demonstrate the Concept

## 1. Simple Example

Consider the following product dataset:

| Product | Quantity | Unit_Price |
|---|---:|---:|
| Pen | 10 | 5.50 |
| Notebook | 4 | 40.00 |
| Pencil | 15 | 3.00 |

`Quantity` and `Unit_Price` are numerical features because they represent quantities and prices.

For example, the total value for the first product is:

Total Value = Quantity × Unit Price = 10 × 5.50 = 55.00

## 2. Real-World Example

A fitness application records a person's weight, distance walked, and daily step count. These numerical values help summarize physical activity and track changes over time.

## 3. Business Example

A retail company analyzes product quantities and unit prices to calculate sales values, compare product performance, and understand revenue patterns.

## 4. AI/ML Use Case

A sales prediction model may use historical prices, quantities, and other relevant numerical inputs to predict future sales.

Before using these features, an engineer should check missing values, unusual observations, and whether the values are appropriate for the prediction objective.

## 5. Importance in Data Analysis

Numerical features allow us to calculate descriptive statistics, examine distributions, compare values, identify outliers, and explore relationships between variables.

These checks help us decide whether further data cleaning or transformation is necessary.

In [9]:

# Identify columns stored with numerical data types
numerical_data = df.select_dtypes(include=np.number)

print("Numerical Columns:")
print(numerical_data.columns.tolist())

# Display the first five records of numerical columns
print("\nNumerical Data Preview:")
display(numerical_data.head())

# Calculate descriptive statistics
print("\nDescriptive Statistics:")
display(numerical_data.describe())

Numerical Columns:
['Quantity', 'Price', 'Customer ID']

Numerical Data Preview:

   Quantity  Price  Customer ID
0        12   6.95      13085.0
1        12   6.75      13085.0
2        12   6.75      13085.0
3        48   2.10      13085.0
4        24   1.25      13085.0

Descriptive Statistics:

            Quantity          Price    Customer ID
count  525461.000000  525461.000000  417534.000000
mean       10.337667       4.688834   15360.645478
std       107.424110     146.126914    1680.811316
min     -9600.000000  -53594.360000   12346.000000
25%         1.000000       1.250000   13983.000000
50%         3.000000       2.100000   15311.000000
75%        10.000000       4.210000   16799.000000
max     19152.000000   25111.090000   18287.000000

# Step 3: Code Explanation and Output Interpretation

## 1. What Does the Code Do?

The code identifies columns stored with numerical data types, displays a preview of those columns, and calculates descriptive statistics for their values.

## 2. Why Is Each Method Used?

### `df.select_dtypes(include=np.number)`

This method selects columns whose data types are numerical, such as integers and floating-point numbers.

**Why is it used?**

It helps us quickly identify columns that may support numerical analysis without manually checking every column.

**Important limitation:** This method identifies columns by their stored data types, not by their business meaning. Numeric identifiers may also appear in the result.

### `numerical_data.columns.tolist()`

The `columns` attribute retrieves the selected column names, and `tolist()` converts them into a standard Python list.

**Why is it used?**

It makes the numerical columns easy to review and document.

### `numerical_data.head()`

The `head()` method returns the first five rows by default.

**Why is it used?**

It lets us inspect actual values and check whether the selected columns contain plausible data.

### `numerical_data.describe()`

This method calculates summary statistics for numerical columns.

- **count:** Number of non-missing values.
- **mean:** Arithmetic average.
- **std:** Standard deviation, which measures the spread of values.
- **min:** Minimum observed value.
- **25%:** First quartile.
- **50%:** Median.
- **75%:** Third quartile.
- **max:** Maximum observed value.

**Why is it used?**

These statistics help us understand the distribution, scale, and variation of numerical data.

## 3. What Does the Output Mean?

The first output lists the columns stored as numerical data types. The preview shows their actual values.

The descriptive statistics summarize each selected column. For example, a negative minimum in `Quantity` may indicate a return or cancellation transaction, so it should be investigated rather than automatically removed.

The count may differ between columns if some values are missing.

## 4. What Insights Can Be Obtained?

We can identify the range and spread of numerical values, compare the mean with the median, and detect values that may require further investigation.

Large differences between the minimum and maximum may indicate a wide distribution or unusual observations.

However, summary statistics alone cannot confirm whether an unusual value is an error. We need to examine its context.

We must also distinguish numerical measurements, such as `Quantity` and `Price`, from numeric-looking identifiers, such as `Customer ID`.

## 5. How Can This Affect an ML Pipeline?

Numerical inspection helps determine whether features require missing-value handling, outlier investigation, scaling, or transformation.

Incorrectly treating identifiers as measurements can introduce misleading patterns into a model. Therefore, feature meaning must be checked in addition to data type.

The appropriate preprocessing depends on the feature, the business objective, and the Machine Learning algorithm being used.

# Step 1: Understand the Concept — Categorical Features

## What Are Categorical Features?

Categorical features are columns that represent groups, labels, names, or categories instead of numerical measurements.

They help us classify data into different groups based on their values.

### Examples
- Country: United Kingdom, France, Germany
- Product Category: Electronics, Clothing, Furniture
- Payment Method: Cash, Card, Online
- Gender: Male, Female

### Categorical Features in Online Retail II

- `Country`: Represents the country where a customer is located.
- `Description`: Represents the name or description of a product.
- `Invoice`: Identifies an invoice and should not automatically be treated as a numerical measurement.

### Types of Categorical Features

1. **Nominal Features:** Categories without a natural order, such as Country and Product Description.
2. **Ordinal Features:** Categories with a meaningful order, such as Low, Medium, and High.

### Why Are Categorical Features Important?

- They help us understand groups within a dataset.
- They allow us to compare business performance across categories.
- They help identify customer locations and popular products.
- They can be converted into numerical representations before being used by many machine learning models.

**Conclusion:** Categorical features describe which group or category a record belongs to.

# Step 2: Demonstrate the Concept — Categorical Features

## 1. Simple Example

Consider the following product data:

| Product | Country | Category |
|---|---|---|
| Laptop | India | Electronics |
| Shirt | India | Clothing |
| Phone | France | Electronics |

Here, `Country` and `Category` are categorical features because their values represent groups.

## 2. Real-World Example

An online shopping company stores product descriptions, customer countries, and payment methods. These categories help the company organize and understand its transactions.

## 3. Business Example

An e-commerce business can group sales by country to identify which countries generate more revenue. It can also analyze product descriptions to find frequently purchased products.

## 4. AI/ML Use Case

Categorical features can be used in machine learning tasks such as customer segmentation, product recommendation, and sales prediction.

For example, a sales prediction model may use a product category or country as an input feature.

Before using categorical values in many machine learning models, we may need to encode them into numerical values.

## 5. Importance During Data Analysis

- Identify different groups in the dataset.
- Compare transactions across countries.
- Find frequently appearing product descriptions.
- Detect missing or inconsistent category values.
- Prepare categorical data for machine learning.

**Conclusion:** Categorical features help us group, compare, and analyze data meaningfully.

In [10]:

# Identify columns stored with text or categorical data types
categorical_data = df.select_dtypes(include=["object", "category"])

# Display categorical column names
print("Categorical Columns:")
print(categorical_data.columns.tolist())

# Display the first five records of categorical columns
print("\nCategorical Data Preview:")
display(categorical_data.head())

# Count the unique values in each categorical column
print("\nUnique Values in Each Categorical Column:")
display(categorical_data.nunique())

# Display the most frequent values in selected columns
print("\nMost Frequent Countries:")
display(df["Country"].value_counts().head(10))

print("\nMost Frequent Product Descriptions:")
display(df["Description"].value_counts().head(10))

Categorical Columns:
['Invoice', 'StockCode', 'Description', 'Country']

Categorical Data Preview:

C:\Users\hh213\AppData\Local\Temp\ipykernel_14420\473911521.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_data = df.select_dtypes(include=["object", "category"])

  Invoice StockCode                          Description         Country
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS  United Kingdom
1  489434    79323P                   PINK CHERRY LIGHTS  United Kingdom
2  489434    79323W                  WHITE CHERRY LIGHTS  United Kingdom
3  489434     22041         RECORD FRAME 7" SINGLE SIZE   United Kingdom
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX  United Kingdom

Unique Values in Each Categorical Column:

Invoice        28816
StockCode       4632
Description     4681
Country           40
dtype: int64

Most Frequent Countries:

Country
United Kingdom     485852
EIRE                 9670
Germany              8129
France               5772
Netherlands          2769
Spain                1278
Switzerland          1187
Portugal             1101
Belgium              1054
Channel Islands       906
Name: count, dtype: int64

Most Frequent Product Descriptions:

Description
WHITE HANGING HEART T-LIGHT HOLDER    3549
REGENCY CAKESTAND 3 TIER              2212
STRAWBERRY CERAMIC TRINKET BOX        1843
PACK OF 72 RETRO SPOT CAKE CASES      1466
ASSORTED COLOUR BIRD ORNAMENT         1457
60 TEATIME FAIRY CAKE CASES           1400
HOME BUILDING BLOCK WORD              1386
JUMBO BAG RED RETROSPOT               1310
LUNCH BAG RED SPOTTY                  1274
REX CASH+CARRY JUMBO SHOPPER          1232
Name: count, dtype: int64

# Step 3: Code Explanation — Categorical Features

## 1. Selecting Categorical Columns

```python
categorical_data = df.select_dtypes(include=["object", "category"])
```

- `df` refers to the Online Retail II DataFrame.
- `select_dtypes()` selects columns based on their data types.
- `include=["object", "category"]` selects columns stored as text or as Pandas categorical data.
- `categorical_data` stores the selected columns.

**Why is it used?**

It helps us identify columns that may contain categorical information without manually checking every column.

**Important:** Some categorical columns may be stored as numbers, and some numeric-looking identifiers may have different meanings. Data types alone cannot identify every category correctly.

## 2. Displaying Categorical Column Names

```python
print(categorical_data.columns.tolist())
```

- `columns` returns the selected column names.
- `tolist()` converts the column names into a Python list.
- `print()` displays the list.

**What does the output mean?**

It shows the columns selected as text or categorical data, such as `Country` and `Description`.

## 3. Viewing the First Five Records

```python
display(categorical_data.head())
```

- `head()` returns the first five rows by default.
- `display()` presents the result as a readable table in Jupyter Notebook.

**Why is it used?**

It allows us to inspect actual category values and check whether they look correct.

## 4. Counting Unique Values

```python
display(categorical_data.nunique())
```

- `nunique()` counts the distinct, non-missing values in each selected column.
- The result shows how many different values each column contains.

**What insights can we obtain?**

- A Country column with a limited number of unique values may be suitable for grouping.
- A Description column with many unique values may contain numerous different products.
- Unexpectedly many category values may indicate spelling differences or inconsistent labels.

By default, missing values are not included in the unique-value count.

## 5. Finding the Most Frequent Countries

```python
display(df["Country"].value_counts().head(10))
```

- `df["Country"]` selects the Country column.
- `value_counts()` counts how often each country appears.
- `head(10)` displays the ten most frequent countries.

**What does the output mean?**

It shows which countries appear most frequently in the transaction records. This counts records, not total sales revenue.

## 6. Finding the Most Frequent Product Descriptions

```python
display(df["Description"].value_counts().head(10))
```

This code counts how frequently each product description appears and displays the ten most frequent descriptions.

It can help identify products that occur often in the transaction data. However, frequent appearance does not necessarily mean the product generated the highest revenue.

By default, `value_counts()` excludes missing values.

## 7. Insights We Can Obtain

- Which countries appear most frequently in the dataset.
- Which product descriptions occur most often.
- How many distinct categories exist in each selected column.
- Whether category values may need cleaning or standardization.

## 8. Impact on the Machine Learning Pipeline

Before training a machine learning model, categorical features may require preprocessing.

Common techniques include:

- **One-Hot Encoding:** Creates separate binary columns for categories, often useful for nominal categories with manageable numbers of values.
- **Ordinal Encoding:** Represents categories with an order using appropriate numerical values.
- **Rare Category Handling:** Groups or manages categories that appear very infrequently when appropriate.

The correct method depends on the feature, the business problem, and the model.

**Final Conclusion:** Categorical feature analysis helps us understand groups in the dataset and prepare category values for further analysis and machine learning.

# Step 1: Understand the Concept — Discrete Features

## What Are Discrete Features?

Discrete features are numerical features that represent countable values. They usually take separate, distinct values rather than any value within a continuous range.

They commonly represent the number of items, people, events, or occurrences.

### Examples
- Number of students: 25
- Number of products purchased: 5
- Number of website visits: 12
- Number of customer complaints: 3

### Discrete Features in Online Retail II

The `Quantity` column represents the quantity of products recorded in a transaction. It is generally a discrete numerical feature because product quantities are counted.

However, this dataset may also contain negative quantities, such as records related to returned items or cancelled transactions. These values should be investigated rather than removed automatically.

### Characteristics of Discrete Features

- Represent countable quantities.
- Often contain whole-number values.
- Can be summarized using counts, totals, minimums, and maximums.
- May contain unusual values that require investigation.

### Why Are Discrete Features Important?

Discrete features help us understand transaction quantities, customer activity, product demand, and the frequency of events.

**Conclusion:** Discrete features represent countable numerical values and can provide useful information during data analysis and machine learning.

# Step 2: Demonstrate the Concept — Discrete Features

## 1. Simple Example

Consider the following shopping data:

| Customer | Number of Products |
|---|---:|
| Customer A | 2 |
| Customer B | 5 |
| Customer C | 3 |

The number of products is a discrete feature because we can count the products.

## 2. Real-World Example

A hospital records the number of patients visiting each day. Values such as 50, 75, and 100 represent countable quantities.

## 3. Business Example

An online retail company analyzes the quantity of products sold to understand demand, identify popular products, and plan inventory.

In Online Retail II, the `Quantity` column can help us investigate how many units are recorded per transaction.

## 4. AI/ML Use Case

Discrete features can be used in demand forecasting, customer behavior analysis, and sales prediction.

For example, historical product quantities may help a business estimate future demand. The model and target must be selected according to the business problem.

## 5. Importance During Data Analysis

- Identify unusually large or negative quantities.
- Understand product demand.
- Calculate total recorded quantities.
- Investigate possible returns or cancellations.
- Prepare meaningful numerical features for machine learning.

**Conclusion:** Discrete features help us analyze countable events and quantities, which are useful for business decisions and predictive models.

In [11]:

# Select the Quantity column
quantity_data = df["Quantity"]

# Display the first ten quantity values
print("First 10 Quantity Values:")
display(quantity_data.head(10))

# Display the data type
print("\nQuantity Data Type:")
print(quantity_data.dtype)

# Calculate descriptive statistics
print("\nQuantity Summary:")
display(quantity_data.describe())

# Count positive, zero, and negative quantity records
print("\nPositive Quantity Records:", (quantity_data > 0).sum())
print("Zero Quantity Records:", (quantity_data == 0).sum())
print("Negative Quantity Records:", (quantity_data < 0).sum())

# Display the number of distinct quantity values
print("\nNumber of Unique Quantity Values:")
print(quantity_data.nunique())

First 10 Quantity Values:

0    12
1    12
2    12
3    48
4    24
5    24
6    24
7    10
8    12
9    12
Name: Quantity, dtype: int64

Quantity Data Type:
int64

Quantity Summary:

count    525461.000000
mean         10.337667
std         107.424110
min       -9600.000000
25%           1.000000
50%           3.000000
75%          10.000000
max       19152.000000
Name: Quantity, dtype: float64

Positive Quantity Records: 513135
Zero Quantity Records: 0
Negative Quantity Records: 12326

Number of Unique Quantity Values:
825

# Step 3: Code Explanation — Discrete Features

## 1. Selecting the Quantity Column

```python
quantity_data = df["Quantity"]
```

- `df` represents the Online Retail II DataFrame.
- `["Quantity"]` selects the Quantity column.
- `quantity_data` stores the selected column as a Pandas Series.

**Why is it used?**

It allows us to analyze product quantities separately from the other columns.

## 2. Displaying the First Ten Values

```python
display(quantity_data.head(10))
```

- `head(10)` returns the first ten records.
- `display()` presents them in a readable format.

**What does the output mean?**

It shows sample quantity values so we can inspect the data and understand how quantities are recorded.

## 3. Checking the Data Type

```python
print(quantity_data.dtype)
```

- `dtype` tells us the data type stored in the column.
- `print()` displays the result.

**Why is it used?**

We need to confirm how Pandas stores the values before performing calculations. A numerical-looking column might sometimes be stored as text.

## 4. Calculating Descriptive Statistics

```python
display(quantity_data.describe())
```

The `describe()` method provides a numerical summary.

- **count:** Number of non-missing values.
- **mean:** Average quantity.
- **std:** Standard deviation, which measures variation.
- **min:** Smallest recorded value.
- **25%, 50%, 75%:** Quartiles, with 50% representing the median.
- **max:** Largest recorded value.

**What insights can we obtain?**

A very large maximum or negative minimum may indicate unusual transactions that need further investigation. The mean can also be influenced by extreme values.

## 5. Counting Positive Quantities

```python
(quantity_data > 0).sum()
```

- `quantity_data > 0` checks which values are greater than zero.
- It produces `True` for positive values and `False` for other values.
- `.sum()` counts the `True` values because `True` behaves like 1 and `False` like 0.

This gives the number of records with positive quantities.

## 6. Counting Zero Quantities

```python
(quantity_data == 0).sum()
```

- `== 0` checks which quantity values equal zero.
- `.sum()` counts the matching records.

This helps identify records with zero quantities, which may need investigation.

## 7. Counting Negative Quantities

```python
(quantity_data < 0).sum()
```

This counts quantity records below zero. In retail transaction data, negative quantities may relate to returns or cancellations.

**Important:** Negative values are not automatically errors. Check the invoice details and business rules before changing or removing them.

## 8. Counting Unique Quantity Values

```python
quantity_data.nunique()
```

- `nunique()` counts distinct, non-missing quantity values.
- It does not count how many times each value appears.

This helps us understand how many different quantity values are present.

## 9. Insights We Can Obtain

- The range of recorded product quantities.
- Whether the column contains zero or negative values.
- How widely quantity values vary.
- Whether unusually large quantities need investigation.

## 10. Impact on the Machine Learning Pipeline

Before using quantity data in a model:

- Investigate extreme values and negative quantities.
- Decide how returns and cancellations should be represented.
- Check for missing values.
- Select suitable features and define the prediction target.
- Apply preprocessing based on the selected model and business objective.

**Final Conclusion:** Discrete feature analysis helps us understand countable values, detect unusual records, and prepare numerical data for reliable analysis and machine learning.

# Step 1: Understand the Concept — Continuous Features

## What Are Continuous Features?

Continuous features are numerical features that represent measurable quantities. In principle, they can take many different values within a range, including decimal values.

They are commonly used to represent measurements such as price, height, weight, distance, and temperature.

### Examples
- Product price: 49.99
- Height: 165.5 cm
- Weight: 62.75 kg
- Temperature: 28.6°C
- Distance: 12.45 km

### Continuous Features in Online Retail II

The `Price` column represents the unit price of a product in a transaction. It can be treated as a continuous numerical feature for many data analysis tasks.

The actual recorded values may follow currency precision rules, so the values may not contain every possible decimal number.

### Characteristics of Continuous Features

- Represent measurable quantities.
- May contain decimal values.
- Can be summarized using averages, minimums, maximums, and standard deviations.
- May contain extreme values that require investigation.

### Why Are Continuous Features Important?

Continuous features help us understand price variation, spending patterns, revenue-related measures, and other numerical relationships.

**Conclusion:** Continuous features represent measurable numerical quantities and are useful for statistical analysis, visualization, and machine learning.

# Step 2: Demonstrate the Concept — Continuous Features

## 1. Simple Example

Consider the following product prices:

| Product | Price |
|---|---:|
| Notebook | 25.50 |
| Bag | 499.99 |
| Pen Set | 75.25 |

The `Price` column represents a measurable monetary amount. It is commonly treated as a continuous feature during analysis.

## 2. Real-World Example

A fitness application records a person's weight as 62.5 kg or 62.8 kg. Weight is a continuous measurement because it can vary across a range of values.

## 3. Business Example

An online retail company analyzes product prices to compare pricing patterns, identify unusually expensive products, and understand differences between product groups.

In Online Retail II, the `Price` column can help us investigate unit-price variation.

## 4. AI/ML Use Case

Continuous features can be used in sales prediction, demand forecasting, and price-related prediction tasks.

For example, unit price may be used as an input feature to predict transaction revenue or product demand, depending on the available data and prediction objective.

## 5. Importance During Data Analysis

- Understand the distribution of product prices.
- Calculate averages and other summary statistics.
- Identify unusually high or low values.
- Compare prices across products or countries.
- Prepare numerical features for machine learning.

**Conclusion:** Continuous features help us analyze measurements and understand numerical patterns in real-world data.

In [12]:

# Select the Price column
price_data = df["Price"]

# Display the first ten price values
print("First 10 Price Values:")
display(price_data.head(10))

# Check the data type
print("\nPrice Data Type:")
print(price_data.dtype)

# Calculate descriptive statistics
print("\nPrice Summary:")
display(price_data.describe())

# Count zero and negative price records
print("\nZero Price Records:", (price_data == 0).sum())
print("Negative Price Records:", (price_data < 0).sum())

# Display the number of distinct price values
print("\nNumber of Unique Price Values:")
print(price_data.nunique())

# Calculate the average unit price
print("\nAverage Unit Price:")
print(price_data.mean())

First 10 Price Values:

0    6.95
1    6.75
2    6.75
3    2.10
4    1.25
5    1.65
6    1.25
7    5.95
8    2.55
9    3.75
Name: Price, dtype: float64

Price Data Type:
float64

Price Summary:

count    525461.000000
mean          4.688834
std         146.126914
min      -53594.360000
25%           1.250000
50%           2.100000
75%           4.210000
max       25111.090000
Name: Price, dtype: float64

Zero Price Records: 3687
Negative Price Records: 3

Number of Unique Price Values:
1606

Average Unit Price:
4.688834478676819

# Step 3: Code Explanation — Continuous Features

## 1. Selecting the Price Column

```python id="a9k7l2"
price_data = df["Price"]
```

- `df` is the Online Retail II DataFrame.
- `["Price"]` selects the Price column.
- `price_data` stores the selected column as a Pandas Series.

**Why is it used?**

It allows us to analyze unit prices independently from other dataset columns.

## 2. Displaying the First Ten Values

```python id="c3m8v1"
display(price_data.head(10))
```

- `head(10)` returns the first ten records.
- `display()` shows the values in a readable format.

**What does the output mean?**

It helps us inspect actual prices and understand how they are recorded.

## 3. Checking the Data Type

```python id="f5q2w9"
print(price_data.dtype)
```

The `dtype` attribute shows the data type stored in the column.

For example, a floating-point data type can store decimal values.

**Why is it used?**

We need to confirm that the price values are stored numerically before performing calculations.

## 4. Calculating Descriptive Statistics

```python id="g1r6x4"
display(price_data.describe())
```

The `describe()` method summarizes the numerical column.

- **count:** Number of non-missing price values.
- **mean:** Average unit price.
- **std:** Standard deviation, which measures price variation.
- **min:** Minimum recorded price.
- **25%, 50%, 75%:** Quartiles; 50% is the median.
- **max:** Maximum recorded price.

**What insights can we obtain?**

We can understand the typical price range and check whether some prices are unusually high or low.

The mean may be influenced by extreme values, so it can be useful to compare the mean with the median.

## 5. Counting Zero Price Records

```python id="h4s8d6"
(price_data == 0).sum()
```

- `price_data == 0` checks whether each price equals zero.
- The result contains `True` or `False` values.
- `.sum()` counts the matching records.

This helps us identify transactions with zero unit prices.

A zero price is worth investigating, but it should not automatically be treated as an error without checking the business context.

## 6. Counting Negative Price Records

```python id="j7p3n5"
(price_data < 0).sum()
```

This counts the number of records with negative prices.

Negative unit prices may indicate unusual records or data-quality issues that require investigation.

## 7. Counting Unique Price Values

```python id="k2t9b4"
price_data.nunique()
```

`nunique()` counts the distinct non-missing prices.

It helps us understand how many different price values appear in the dataset. It does not count the frequency of each price.

## 8. Calculating the Average Unit Price

```python id="m6v1z8"
price_data.mean()
```

- `mean()` calculates the arithmetic average of the non-missing values by default.
- It helps summarize the average recorded unit price.

**Important:** This is the average unit price per transaction line, not the average amount spent per customer. Each row may represent a different transaction line, and the average does not account for the quantity purchased.

## 9. Insights We Can Obtain

- The range and average of unit prices.
- How much prices vary across transaction records.
- Whether zero or negative prices exist.
- Whether extreme prices require further investigation.

## 10. Impact on the Machine Learning Pipeline

Before using price-related features in a model:

- Check missing values and unusual prices.
- Investigate extreme values before deciding how to handle them.
- Consider scaling numerical features if required by the model.
- Avoid data leakage when calculating preprocessing values.
- Confirm that the price feature is available at the time a prediction would be made.

**Final Conclusion:** Continuous feature analysis helps us understand numerical measurements, identify unusual values, and prepare suitable features for data analysis and machine learning.

# Step 1: Understand the Concept — Identifier Columns

## What Are Identifier Columns?

Identifier columns are columns used to distinguish or identify records, customers, products, invoices, or other entities in a dataset.

They may contain numbers, letters, or a combination of both.

### Examples
- Customer ID: C1025
- Invoice Number: INV1001
- Product Code: P205
- Employee ID: E501

### Identifier Columns in Online Retail II

- `Invoice`: Identifies an invoice or transaction.
- `StockCode`: Represents a product or stock code.
- `Customer ID`: Identifies a customer when the value is available.

### Characteristics of Identifier Columns

- They help distinguish records or entities.
- They may be stored as text or numbers.
- Their numerical values usually do not represent measurable quantities.
- Some identifiers may be missing or repeated, depending on the dataset structure.

### Why Are Identifier Columns Important?

- They help connect related transaction records.
- They support customer-level and invoice-level analysis.
- They help identify duplicate records or repeated transactions.
- They can be used to group data by customer, invoice, or product.

### Important Note for Machine Learning

An identifier is not automatically a useful predictive feature. Using raw IDs as model inputs can cause a model to learn meaningless patterns, especially when IDs are arbitrary or linked to record order.

Identifiers should be evaluated based on the prediction objective and the risk of data leakage.

**Conclusion:** Identifier columns help us recognize and connect records, but they should not automatically be treated as ordinary numerical features.

# Step 2: Demonstrate the Concept — Identifier Columns

## 1. Simple Example

Consider the following customer data:

| Customer ID | Customer Name | Age |
|---|---|---:|
| 101 | Arun | 25 |
| 102 | Priya | 28 |
| 103 | Ravi | 30 |

Here, `Customer ID` identifies each customer, while `Age` represents a measurable numerical feature.

Although Customer ID contains numbers, the difference between IDs 101 and 102 does not mean the customers differ by one unit of any measurable quantity.

## 2. Real-World Example

A hospital assigns a unique patient ID to each patient. Doctors use this ID to retrieve records without relying only on the patient's name.

## 3. Business Example

An online retail company uses invoice numbers to group products belonging to the same transaction. It can also use customer IDs to analyze purchase history when customer information is available.

## 4. AI/ML Use Case

Identifiers can help organize data before model training. For example, customer IDs can be used to group transactions and create customer-level features.

However, raw customer IDs are often excluded from model inputs unless there is a clear, justified reason to use them.

## 5. Importance During Data Analysis

- Identify customers and invoices.
- Connect transaction records.
- Count unique customers, invoices, and products.
- Investigate duplicate or missing identifiers.
- Avoid treating arbitrary IDs as meaningful numerical measurements.

**Conclusion:** Identifier columns are useful for data organization and grouping, but their role must be understood before using them in machine learning.

In [13]:

# Select the identifier columns
identifier_columns = ["Invoice", "StockCode", "Customer ID"]

# Display sample identifier values
print("Identifier Column Preview:")
display(df[identifier_columns].head(10))

# Count unique values in each identifier column
print("\nUnique Identifier Counts:")
display(df[identifier_columns].nunique())

# Count missing values in each identifier column
print("\nMissing Identifier Values:")
display(df[identifier_columns].isnull().sum())

# Count repeated invoice values
print("\nNumber of Unique Invoices:")
print(df["Invoice"].nunique())

# Count unique customers, excluding missing values
print("\nNumber of Unique Customers:")
print(df["Customer ID"].nunique())

# Count unique product codes
print("\nNumber of Unique Stock Codes:")
print(df["StockCode"].nunique())

Identifier Column Preview:

  Invoice StockCode  Customer ID
0  489434     85048      13085.0
1  489434    79323P      13085.0
2  489434    79323W      13085.0
3  489434     22041      13085.0
4  489434     21232      13085.0
5  489434     22064      13085.0
6  489434     21871      13085.0
7  489434     21523      13085.0
8  489435     22350      13085.0
9  489435     22349      13085.0

Unique Identifier Counts:

Invoice        28816
StockCode       4632
Customer ID     4383
dtype: int64

Missing Identifier Values:

Invoice             0
StockCode           0
Customer ID    107927
dtype: int64

Number of Unique Invoices:
28816

Number of Unique Customers:
4383

Number of Unique Stock Codes:
4632

# Step 3: Code Explanation — Identifier Columns

## 1. Selecting Identifier Columns

```python
identifier_columns = ["Invoice", "StockCode", "Customer ID"]
```

- `identifier_columns` is a Python list.
- The list stores the names of the three columns we want to inspect.
- These columns represent invoice, product, and customer identifiers.

**Why is it used?**

Keeping the column names in a list makes it easier to select and analyze them together.

## 2. Displaying Identifier Values

```python
display(df[identifier_columns].head(10))
```

- `df[identifier_columns]` selects the listed columns from the DataFrame.
- `head(10)` returns the first ten rows.
- `display()` shows the result as a table.

**What does the output mean?**

It shows sample invoice numbers, product codes, and customer IDs. You can check how the identifiers are recorded and whether any values are missing.

## 3. Counting Unique Identifiers

```python
display(df[identifier_columns].nunique())
```

- `nunique()` counts the distinct, non-missing values in each selected column.
- The output contains one unique-value count per identifier column.

**Why is it used?**

It helps us estimate how many distinct invoices, products, and customers appear in the data.

The number of unique invoice values is not necessarily the same as the number of rows because one invoice can contain multiple transaction lines.

## 4. Checking Missing Identifier Values

```python
display(df[identifier_columns].isnull().sum())
```

- `isnull()` identifies missing values and returns `True` for missing entries.
- `.sum()` counts the missing entries in each column.
- `display()` presents the counts.

**What does the output mean?**

It shows how many records lack an invoice number, stock code, or customer ID.

Missing customer IDs may be present in Online Retail II. Their presence should be documented and handled according to the analysis objective.

## 5. Counting Unique Invoices

```python
df["Invoice"].nunique()
```

- `df["Invoice"]` selects the invoice column.
- `nunique()` counts distinct invoice values while excluding missing values.

**What insight can we obtain?**

It helps us understand how many different invoices are represented in the dataset.

## 6. Counting Unique Customers

```python
df["Customer ID"].nunique()
```

This counts the distinct non-missing customer IDs.

It helps us understand how many identifiable customers appear in the records. It does not count records with missing customer IDs as additional customers.

## 7. Counting Unique Products

```python
df["StockCode"].nunique()
```

This counts distinct stock codes. It helps estimate the number of different product codes represented in the transaction data.

A stock code is not guaranteed to represent a unique physical product in every case, so unusual codes may need further investigation.

## 8. Insights We Can Obtain

- How many unique invoices are present.
- How many distinct customers can be identified.
- How many stock codes appear.
- Whether identifier columns contain missing values.
- Why the number of records differs from the number of unique invoices.

## 9. Impact on the Machine Learning Pipeline

- Decide whether identifiers should be excluded from model inputs.
- Use identifiers to group records when appropriate.
- Check for missing or inconsistent identifiers.
- Avoid using identifiers that reveal the target or create data leakage.
- Consider customer-level or invoice-level grouping when splitting data, if required by the prediction objective.

**Final Conclusion:** Identifier analysis helps us organize transaction data, understand unique entities, and prevent inappropriate use of arbitrary identifiers in machine learning.

# Step 1: Understand the Concept — Target Variable

## What Is a Target Variable?

A target variable is the value that a machine learning model is designed to predict. It is also called the dependent variable or prediction target.

The target variable depends on the problem we want to solve.

### Examples
- Student performance prediction: Marks
- House price prediction: House Price
- Customer churn prediction: Churn Status
- Sales prediction: Sales Amount

### Target Variable in Online Retail II

Online Retail II does not have one predefined target variable for every machine learning task. The target must be selected or created according to the business objective.

For example:
- Sales amount prediction: A transaction-line amount could be calculated using Quantity multiplied by Price.
- Future purchase prediction: A target could indicate whether a customer purchases during a defined future period.
- Country classification: Country could be the target if the goal is to predict a transaction's country.

### Characteristics of a Target Variable

- Represents the value or outcome to predict.
- Must match the business or analytical objective.
- Can be numerical or categorical.
- Must be prepared carefully to avoid data leakage.

### Types of Target Variables

1. **Numerical Target:** A measurable number, such as sales amount or house price.
2. **Categorical Target:** A class or label, such as churn or non-churn.

### Why Is the Target Variable Important?

The target determines the machine learning task, the model evaluation method, and the information the model learns to predict.

**Conclusion:** A target variable defines what a machine learning model should predict.

# Step 2: Demonstrate the Concept — Target Variable

## 1. Simple Example

Consider the following student data:

| Study Hours | Attendance (%) | Marks |
|---:|---:|---:|
| 2 | 75 | 60 |
| 4 | 85 | 78 |
| 6 | 95 | 92 |

If the goal is to predict student marks:
- Study Hours and Attendance are input features.
- Marks is the target variable.

The model learns relationships between the inputs and the marks in the training data.

## 2. Real-World Example

A real estate company uses house size, location, and number of bedrooms to predict a house's selling price. In this task, selling price is the target variable.

## 3. Business Example

An online retail business wants to estimate transaction-line sales amounts. It can define a target using quantity multiplied by unit price, while deciding how to handle returns, cancellations, and unusual transactions.

## 4. AI/ML Use Case

Target variables help determine the machine learning task:
- Numerical target: Often a regression problem.
- Categorical target: Often a classification problem.

For example, predicting transaction amount is generally regression, while predicting whether a customer will purchase is generally classification.

## 5. Importance During Data Analysis

- Clarify the business question.
- Identify the correct output to predict.
- Select suitable input features.
- Choose an appropriate model and evaluation metric.
- Prevent target leakage by ensuring the inputs do not contain information unavailable at prediction time.

**Conclusion:** Choosing a suitable target variable is an essential step before building a machine learning model.

In [14]:

import pandas as pd

# Create a sample dataset for target variable demonstration
student_data = pd.DataFrame({
    "Study_Hours": [2, 4, 6, 3, 5],
    "Attendance": [75, 85, 95, 80, 90],
    "Marks": [60, 78, 92, 70, 85]
})

# Select input features
X = student_data[["Study_Hours", "Attendance"]]

# Select the target variable
y = student_data["Marks"]

# Display the input features and target
print("Input Features (X):")
display(X)

print("\nTarget Variable (y):")
display(y)

# Display the available Online Retail II columns
print("\nOnline Retail II Columns:")
print(df.columns.tolist())

Input Features (X):

   Study_Hours  Attendance
0            2          75
1            4          85
2            6          95
3            3          80
4            5          90

Target Variable (y):

0    60
1    78
2    92
3    70
4    85
Name: Marks, dtype: int64

Online Retail II Columns:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

# Step 3: Code Explanation — Target Variable

## 1. Importing Pandas

```python
import pandas as pd
```

- `pandas` is a Python library used to work with tabular data.
- `pd` is the common short alias for Pandas.

**Why is it used?**

We use Pandas to create and manipulate the sample student dataset.

## 2. Creating a Sample Dataset

```python
student_data = pd.DataFrame({
    "Study_Hours": [2, 4, 6, 3, 5],
    "Attendance": [75, 85, 95, 80, 90],
    "Marks": [60, 78, 92, 70, 85]
})
```

- `pd.DataFrame()` creates a table from the supplied data.
- Each dictionary key becomes a column name.
- Each list contains the values for that column.
- `student_data` stores the resulting DataFrame.

**What does the output represent?**

Each row represents one student. Study Hours and Attendance are possible inputs, while Marks is the outcome we want to predict.

This is a demonstration dataset, not actual student data from the Online Retail II dataset.

## 3. Selecting Input Features

```python
X = student_data[["Study_Hours", "Attendance"]]
```

- `student_data[...]` selects columns from the DataFrame.
- The list contains the two input column names.
- `X` stores the selected input features.

**Why are two sets of square brackets used?**

The inner brackets create a list of column names. The outer brackets select those columns from the DataFrame, keeping the result as a DataFrame.

## 4. Selecting the Target Variable

```python
y = student_data["Marks"]
```

- `student_data["Marks"]` selects the Marks column.
- `y` stores the target as a Pandas Series.

**Why is it used?**

It separates the value the model should predict from the input features.

In this example, the goal is to predict Marks using Study Hours and Attendance.

## 5. Displaying the Input Features

```python
print("Input Features (X):")
display(X)
```

- `print()` displays a descriptive label.
- `display(X)` shows the selected input columns as a table.

**What does the output mean?**

The output contains Study Hours and Attendance, which will serve as the model inputs in this example.

## 6. Displaying the Target

```python
print("\nTarget Variable (y):")
display(y)
```

- `\n` inserts a blank line before the label.
- `display(y)` displays the Marks values.

**What does the output mean?**

The output shows the values the model would learn to predict during training.

The input and target rows must remain correctly aligned so that each student's inputs match their marks.

## 7. Inspecting Online Retail II Columns

```python
print(df.columns.tolist())
```

- `df.columns` retrieves the column names from the actual retail dataset.
- `tolist()` converts the column names into a Python list.
- `print()` displays them.

**Why is it used?**

It helps us inspect the available columns before defining a business-specific target.

Online Retail II does not have a predefined target column for all prediction tasks. We must choose or create one according to the problem.

## 8. Insights We Can Obtain

- Which columns are inputs and which column is the target in the demonstration.
- How a numerical target differs from its input features.
- Which columns are available in the retail dataset.
- Why target selection depends on the business question.

## 9. Impact on the Machine Learning Pipeline

- Define the prediction objective.
- Select or construct a suitable target.
- Separate input features (`X`) and target (`y`).
- Check missing and invalid target values.
- Split data into training and testing sets appropriately.
- Choose a suitable model and evaluation metric.
- Prevent target leakage and ensure that the target is available for training.

**Final Conclusion:** The target variable defines what the model learns to predict. Correct target selection is necessary for building a meaningful machine learning solution.

# Step 1: Understand the Concept — Metadata

## What Is Metadata?

Metadata means "data about the data." It describes the structure, source, characteristics, and other important details of a dataset.

Metadata helps us understand what a dataset contains before performing detailed analysis.

### Examples of Metadata

- Dataset name
- Data source
- Number of rows and columns
- Column names
- Column data types
- Missing value information
- Date range covered by the data
- Meaning of individual columns

### Metadata in Online Retail II

For the Online Retail II dataset, useful metadata includes:

- **Dataset Name:** Online Retail II
- **Source:** UCI Machine Learning Repository
- **Domain:** Online retail and e-commerce transactions
- **Columns:** Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, and Country
- **Data Types:** Numerical, text, and date/time types
- **Target Variable:** No single predefined target for every machine learning problem

### Why Is Metadata Important?

- Helps us understand the dataset structure.
- Makes it easier to identify numerical, categorical, and date/time columns.
- Helps us find missing values and possible data-quality issues.
- Supports documentation and reproducibility.
- Helps us prepare the dataset for further analysis and machine learning.

**Conclusion:** Metadata describes a dataset and helps us understand its structure and characteristics before analyzing its contents.

# Step 2: Demonstrate the Concept — Metadata

## 1. Simple Example

Consider a student dataset with the following details:

| Metadata Item | Example |
|---|---|
| Dataset Name | Student Performance |
| Number of Rows | 100 |
| Number of Columns | 5 |
| Numerical Column | Age |
| Categorical Column | Department |
| Target Column | Marks |

These details describe the dataset and help us understand its structure.

## 2. Real-World Example

A photo may have metadata such as file size, image dimensions, creation date, and file format. This information describes the image without being the actual image content.

## 3. Business Example

An e-commerce analyst documents a transaction dataset's source, date range, column meanings, missing values, and data types before calculating sales or customer activity.

This documentation helps other team members understand and reuse the data correctly.

## 4. AI/ML Use Case

Metadata helps data scientists identify suitable input columns, detect data-quality issues, and understand whether the available data matches the prediction problem.

For example, identifying a date column can help an analyst create time-based features for forecasting.

## 5. Importance During Data Analysis

- Understand the dataset's origin and structure.
- Verify row and column counts.
- Check data types.
- Identify missing values.
- Document assumptions and limitations.
- Improve the reliability and reproducibility of analysis.

**Conclusion:** Metadata provides essential context for understanding, documenting, and preparing data for analysis and machine learning.

In [15]:

# Display the dataset name and source
print("Dataset Name: Online Retail II")
print("Dataset Source: UCI Machine Learning Repository")

# Display the number of rows and columns
print("\nDataset Dimensions:")
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

# Display column names and data types
print("\nColumn Names and Data Types:")
display(df.dtypes)

# Display dataset information
print("\nDataset Information:")
df.info()

# Count missing values in each column
print("\nMissing Values:")
display(df.isnull().sum())

# Display the date range if InvoiceDate is available
if "InvoiceDate" in df.columns:
    print("\nInvoice Date Range:")
    print("Earliest Date:", df["InvoiceDate"].min())
    print("Latest Date:", df["InvoiceDate"].max())

Dataset Name: Online Retail II
Dataset Source: UCI Machine Learning Repository

Dataset Dimensions:
Number of Rows: 525461
Number of Columns: 8

Column Names and Data Types:

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID           float64
Country                   str
dtype: object

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[us]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 38.8+ MB

Missing Values:

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

Invoice Date Range:
Earliest Date: 2009-12-01 07:45:00
Latest Date: 2010-12-09 20:01:00

# Step 3: Code Explanation — Metadata

## 1. Displaying Dataset Name and Source

```python id="v7a2m9"
print("Dataset Name: Online Retail II")
print("Dataset Source: UCI Machine Learning Repository")
```

- `print()` displays the supplied text.
- These statements document the dataset's name and source.

**Why is it used?**

Recording the source makes the analysis easier to document and reproduce. These are manually entered labels, not values automatically retrieved from the DataFrame.

## 2. Checking Dataset Dimensions

```python id="r4k8p1"
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])
```

- `df.shape` returns a tuple containing the number of rows and columns.
- `df.shape[0]` returns the row count.
- `df.shape[1]` returns the column count.
- `print()` displays the results.

**What does the output mean?**

The row count indicates how many records are currently loaded. The column count indicates how many columns are present.

The results describe your loaded DataFrame and may differ from the full published dataset if only one worksheet or a subset was loaded.

## 3. Displaying Column Data Types

```python id="c2n6w5"
display(df.dtypes)
```

- `df.dtypes` returns the stored data type of each column.
- `display()` presents the result in a readable format.

**Why is it used?**

It helps us identify columns stored as integers, floating-point numbers, text, or dates.

A column's stored data type does not always describe its business meaning. For example, a numeric Customer ID is an identifier rather than a measurement.

## 4. Displaying Dataset Information

```python id="t9x3b6"
df.info()
```

`info()` displays a summary of the DataFrame, including:

- Column names.
- Non-null value counts.
- Data types.
- Memory usage.

**What does the output mean?**

A difference between the total row count and a column's non-null count indicates that the column contains missing values.

The output helps us understand the structure and completeness of the loaded data.

## 5. Counting Missing Values

```python id="h5q1z7"
display(df.isnull().sum())
```

- `isnull()` checks every cell for missing values.
- `.sum()` counts the missing values in each column.
- `display()` presents the counts.

**Why is it used?**

Missing values may affect calculations, visualizations, and model training. We need to understand their distribution before deciding how to handle them.

## 6. Checking the Invoice Date Range

```python id="p8d4j2"
if "InvoiceDate" in df.columns:
    print("Earliest Date:", df["InvoiceDate"].min())
    print("Latest Date:", df["InvoiceDate"].max())
```

- The `if` statement checks whether `InvoiceDate` exists in the DataFrame.
- `df["InvoiceDate"]` selects the date column.
- `min()` returns the earliest date value.
- `max()` returns the latest date value.

**Why is it used?**

The date range helps us understand the period covered by the loaded data. It can also help identify unexpected dates or plan time-based analysis.

This assumes the column is stored in a suitable date/time format. If it is stored as text, convert it to datetime before relying on date calculations.

## 7. Insights We Can Obtain

- The actual number of loaded rows and columns.
- The data types used by Pandas.
- Which columns contain missing values.
- The time period covered by the loaded records.
- Details needed to document the dataset.

## 8. Impact on the Machine Learning Pipeline

- Confirm that the dataset structure matches expectations.
- Identify columns that need type conversion.
- Plan missing-value handling.
- Document the data source and assumptions.
- Verify that the available date range matches the prediction objective.
- Improve reproducibility by recording dataset details.

**Final Conclusion:** Metadata inspection helps us understand and document the dataset before deeper exploration, cleaning, visualization, and machine learning.

# Step 1: Understand the Concept — Dataset Dimensions

## What Are Dataset Dimensions?

Dataset dimensions describe the size of a dataset in terms of its number of rows and columns.

Rows generally represent records or observations, while columns represent features or variables.

### Example

Consider a dataset containing student information:

| Student ID | Age | Department | Marks |
|---|---:|---|---:|
| 101 | 20 | IT | 85 |
| 102 | 21 | CS | 90 |
| 103 | 22 | IT | 78 |

This dataset has 3 rows and 4 columns.

Its dimensions are represented as `(3, 4)`.

### Dataset Dimensions in Online Retail II

- **Rows:** Transaction-line records in the loaded dataset.
- **Columns:** Available fields, such as Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, and Country.

One invoice may contain multiple transaction lines, so the number of rows is not necessarily equal to the number of invoices.

### Why Are Dataset Dimensions Important?

- Help us understand the size of the dataset.
- Confirm whether the expected data has been loaded.
- Help us estimate data-processing requirements.
- Reveal unexpected changes after filtering or cleaning.
- Provide a basic check before further exploratory data analysis.

**Conclusion:** Dataset dimensions tell us how many records and columns are available for analysis.

# Step 2: Demonstrate the Concept — Dataset Dimensions

## 1. Simple Example

Consider the following dataset:

| Product | Quantity | Price |
|---|---:|---:|
| Notebook | 2 | 25.50 |
| Pen | 5 | 10.00 |
| Bag | 1 | 499.99 |
| Pencil | 3 | 5.00 |

This dataset has 4 rows and 3 columns.

Therefore, its dimensions are `(4, 3)`.

## 2. Real-World Example

A hospital database may contain thousands of patient records and several columns, such as patient ID, age, visit date, and diagnosis.

Dataset dimensions help the hospital understand the size of the available data.

## 3. Business Example

An e-commerce company checks the dimensions of its transaction dataset before calculating sales, comparing countries, or analyzing customer behavior.

If the number of rows unexpectedly decreases after loading or cleaning, the analyst can investigate whether records were filtered out.

## 4. AI/ML Use Case

Dataset dimensions help data scientists understand the amount of data available for training and testing machine learning models.

For example, a dataset with many rows and a manageable number of features may support different experiments from a dataset with very few records and thousands of features.

However, larger dimensions do not automatically mean better data quality or better model performance.

## 5. Importance During Data Analysis

- Verify the loaded dataset size.
- Count the available features.
- Compare dataset size before and after cleaning.
- Detect unexpected filtering or data loss.
- Understand the data available for machine learning.

**Conclusion:** Checking dataset dimensions is a basic but important step in data inspection and exploratory data analysis.

In [16]:

# Display the dataset dimensions
print("Dataset Dimensions:", df.shape)

# Display the number of rows
print("\nNumber of Rows:", df.shape[0])

# Display the number of columns
print("Number of Columns:", df.shape[1])

# Display the column names
print("\nColumn Names:")
print(df.columns.tolist())

# Calculate the total number of cells
total_cells = df.shape[0] * df.shape[1]
print("\nTotal Number of Cells:", total_cells)

# Display the first five records
print("\nFirst Five Records:")
display(df.head())

Dataset Dimensions: (525461, 8)

Number of Rows: 525461
Number of Columns: 8

Column Names:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

Total Number of Cells: 4203688

First Five Records:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

# Step 3: Code Explanation — Dataset Dimensions

## 1. Displaying Dataset Dimensions

```python id="v3k9m2"
print("Dataset Dimensions:", df.shape)
```

- `df` represents the loaded Online Retail II DataFrame.
- `shape` returns a tuple containing the number of rows and columns.
- `print()` displays the result.

For example, if the output is `(1000, 8)`, the DataFrame contains 1,000 rows and 8 columns.

The first number represents rows, and the second represents columns.

## 2. Counting Rows

```python id="r6w2p8"
print("Number of Rows:", df.shape[0])
```

- `df.shape[0]` retrieves the first value from the dimensions tuple.
- It represents the total number of rows currently loaded.

**Why is it used?**

It helps us understand how many records are available for analysis.

## 3. Counting Columns

```python id="a4j7n1"
print("Number of Columns:", df.shape[1])
```

- `df.shape[1]` retrieves the second value from the tuple.
- It represents the total number of columns.

**Why is it used?**

It helps us understand how many fields or features are available in the dataset.

## 4. Displaying Column Names

```python id="m9c5x4"
print(df.columns.tolist())
```

- `df.columns` retrieves the column names.
- `tolist()` converts them into a Python list.
- `print()` displays the list.

**What does the output mean?**

It shows the fields available for further inspection and analysis.

## 5. Calculating the Total Number of Cells

```python id="k2p8f6"
total_cells = df.shape[0] * df.shape[1]
print("Total Number of Cells:", total_cells)
```

- `df.shape[0]` gives the row count.
- `df.shape[1]` gives the column count.
- `*` multiplies the two values.
- `total_cells` stores the result.

For example, a dataset with 100 rows and 8 columns has 800 cells.

**Important:** Total cells include both populated and missing positions.

## 6. Displaying the First Five Records

```python id="c8v5t3"
display(df.head())
```

- `head()` returns the first five rows by default.
- `display()` presents them as a table.

**Why is it used?**

It allows us to connect the dimensions with the actual records and check whether the dataset looks as expected.

## 7. Insights We Can Obtain

- The number of records currently available.
- The number of columns available for analysis.
- The overall size of the DataFrame.
- Whether the loaded columns match our expectations.
- Whether dataset size changes after filtering or cleaning.

## 8. Impact on the Machine Learning Pipeline

- Verify the dataset before preprocessing.
- Confirm the number of input features after selecting columns.
- Check the number of records available for training and testing.
- Monitor data loss during cleaning.
- Understand the approximate scale of data-processing work.

**Final Conclusion:** Dataset dimensions provide a quick overview of dataset size and structure. They help us verify loaded data and prepare for further exploratory data analysis.