# Step 1: Understand the Concept

### Number of Rows

**What is the Number of Rows?**

The number of rows represents the total number of records in a dataset. Each row contains information about one observation or record.

In the Online Retail II dataset, each row generally represents a product transaction line.

**Why is it important?**

- It helps us understand the size of the dataset.
- It tells us how many records are available for analysis.
- It helps us check whether the dataset contains sufficient records for the intended task.
- It provides a starting point for data inspection.

**Conclusion:** Counting rows is one of the first steps in understanding a dataset.

# Step 2: Demonstrate the Concept

### Demonstrating the Number of Rows

**Simple Example**

Consider a student dataset:

| Student | Marks |
|---|---:|
| A | 75 |
| B | 88 |
| C | 92 |

This dataset contains three rows because it has three student records.

**Real-World Example**

An online shopping dataset may contain thousands of transaction records. Each row can represent a product purchased as part of an invoice.

**Business Example**

A business can inspect the number of transaction records to understand how much historical sales data is available for analysis.

**AI/ML Use Case**

The number of records helps us understand the available training data. However, a large number of rows alone does not guarantee a good machine learning model. Data quality and relevance also matter.

**Importance in Data Analysis**

Before analyzing a dataset, we should know how many records it contains so that we can understand its size and plan the next inspection steps.

In [2]:

import pandas as pd
import numpy as np

file_path = "online_retail_II.xlsx"

df = pd.read_excel(file_path, sheet_name="Year 2009-2010")

print("Dataset loaded successfully!")
display(df.head())

Dataset loaded successfully!

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [4]:

# Count the number of rows in the dataset
number_of_rows = len(df)

print("Number of Rows:", number_of_rows)

Number of Rows: 525461

### Code Explanation

**1. `len(df)`**

The `len()` function returns the number of rows in the DataFrame.

For example, if a DataFrame contains 100 records, `len(df)` returns `100`.

**2. `number_of_rows = len(df)`**

This stores the row count in a variable named `number_of_rows`. Storing the result makes it easier to reuse the value later.

**3. `print("Number of Rows:", number_of_rows)`**

The `print()` function displays a descriptive message and the calculated row count.

### What Does the Output Tell Us?

The output shows the total number of records currently loaded into `df`. It does not tell us how many records are unique, how many contain missing values, or how many are valid for analysis.

### Insights We Can Obtain

- Understand the dataset's size.
- Check whether the expected data appears to be loaded.
- Establish a starting point for data-quality checks.

### Impact on the ML Pipeline

The row count helps us understand the amount of data available before data cleaning, feature engineering, and model training. Later, we should also check duplicate records, missing values, and data quality before deciding how to use the dataset.


# Topic 2: Number of Columns
## Step 1: Understand the Concept

### What is the Number of Columns?

The number of columns represents the total number of variables or features available in a dataset. Each column stores a particular type of information.

For example, an online retail dataset may contain columns such as Invoice, StockCode, Description, Quantity, Price, and Country.

### Why Is It Important?

- It helps us understand the structure of a dataset.
- It tells us how many variables are available for analysis.
- It helps identify the information available for business analysis and machine learning.
- It helps us inspect whether the expected columns are present.

**Conclusion:** Counting columns is an important step in understanding the dataset before performing further analysis.

## Step 2: Demonstrate the Concept

### Simple Example

Consider the following student dataset:

| Student | Age | Marks |
|---|---:|---:|
| A | 20 | 75 |
| B | 21 | 88 |
| C | 22 | 92 |

This dataset contains three columns: Student, Age, and Marks.

### Real-World Example

An online retail dataset may contain columns describing invoices, products, quantities, prices, dates, and countries.

### Business Example

A business can inspect its columns to understand which details are available for sales analysis, product analysis, and customer analysis.

### AI/ML Use Case

Columns may provide input features for a machine learning model. Depending on the business problem, a suitable target column may also be selected.

### Importance in Data Analysis

Knowing the number of columns helps us understand the available variables and prepare for data-type inspection, feature identification, and data cleaning.

In [5]:
# Count the number of columns in the dataset
number_of_columns = len(df.columns)

print("Number of Columns:", number_of_columns)

# Display all column names
print("\nColumn Names:")
print(df.columns.tolist())

Number of Columns: 8

Column Names:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

## Step 3: Code Explanation

### 1. `df.columns`

This returns the column labels of the DataFrame.

For the Online Retail II dataset, the columns include Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, and Country.

### 2. `len(df.columns)`

The `len()` function counts the number of column labels.

If the DataFrame contains eight columns, this expression returns 8.

### 3. `number_of_columns = len(df.columns)`

This stores the total column count in a variable named `number_of_columns`.

### 4. `df.columns.tolist()`

The `tolist()` method converts the column labels into a standard Python list, making them easier to display and inspect.

### 5. `print()`

The `print()` function displays the column count and the list of column names.

### What Does the Output Tell Us?

The first output shows the total number of columns in the loaded DataFrame. The second output displays the names of those columns.

The exact count depends on the DataFrame currently loaded into `df`.

### Insights We Can Obtain

- Understand how many variables are available.
- Confirm whether expected columns are present.
- Identify columns that may represent numerical values, categories, dates, or identifiers.

### Impact on the ML Pipeline

Column inspection helps us identify potential input features and possible target variables. Before training a model, we must also check data types, missing values, data quality, and whether each column is relevant to the selected business problem.


# Topic 3: Data Types
## Step 1: Understand the Concept

### What Are Data Types?

Data types describe the kind of values stored in a dataset column. A column may contain integers, decimal numbers, text, or date and time values.

### Common Data Types

- **Integer:** Whole numbers, such as 10 or 25.
- **Float:** Decimal numbers, such as 6.95 or 12.50.
- **Object:** Often used for text or columns containing mixed data.
- **Datetime:** Values representing dates and times.

### Why Are Data Types Important?

- They help us understand the information stored in each column.
- They help identify columns that may need type conversion.
- They support correct calculations and analysis.
- They help prepare data for visualization and machine learning.

**Conclusion:** Checking data types is an important step in understanding and preparing a dataset.


## Step 2: Demonstrate the Concept

### Simple Example

Consider the following data:

| Quantity | Price | Country |
|---:|---:|---|
| 5 | 10.50 | India |
| 3 | 20.00 | Japan |

- Quantity contains whole numbers.
- Price contains decimal numbers.
- Country contains text values.

### Real-World Example

An online retail dataset stores product quantities, prices, invoice dates, and country names. These columns contain different types of information.

### Business Example

A business needs numerical data for calculations, date values for time-based analysis, and categorical data for comparing countries or products.

### AI/ML Use Case

Machine learning algorithms often require data to be converted into suitable numerical representations. Dates may also need to be transformed into useful features.

### Importance in Data Analysis

Correctly identifying data types helps prevent calculation errors and supports appropriate data cleaning, visualization, and feature preparation.

In [6]:

# Display the data type of each column
print("Data Types of All Columns:")
display(df.dtypes)

Data Types of All Columns:

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID           float64
Country                   str
dtype: object


## Code Explanation

### 1. `df.dtypes`

The `dtypes` attribute returns the data type of every column in the DataFrame.

For example:
- `Quantity` may be stored as an integer.
- `Price` may be stored as a floating-point number.
- `Description` may be stored as an object.
- `InvoiceDate` may be stored as an object or a datetime type, depending on how it was loaded.

### 2. `display(df.dtypes)`

The `display()` function presents the column names and their corresponding data types in a readable format.

### What Does the Output Tell Us?

The output helps us understand how Pandas currently interprets each column. The stored type does not always represent the column's real-world meaning. For example, an invoice number may be stored as text even though it contains digits.

### Insights We Can Obtain

- Identify numerical and text columns.
- Check whether date columns are recognized correctly.
- Find columns that may require data type conversion.
- Prepare for more accurate analysis.

### Impact on the ML Pipeline

Data types affect data cleaning, feature engineering, visualization, and model preparation. Incorrectly stored values may need conversion before they can be analyzed or used by a machine learning model.


# Topic 4: Column Names
## Step 1: Understand the Concept

### What Are Column Names?

Column names are labels used to identify the information stored in each column of a dataset.

For example, an online retail dataset may contain column names such as Invoice, StockCode, Description, Quantity, Price, InvoiceDate, Customer ID, and Country.

### Why Are Column Names Important?

- They help us understand what information each column represents.
- They allow us to select specific columns during analysis.
- They help us identify spelling mistakes or unexpected column names.
- They make data cleaning and feature selection easier.

**Conclusion:** Inspecting column names helps us understand the dataset structure and use the correct columns during analysis.


## Step 2: Demonstrate the Concept

### Simple Example

Consider a dataset with these column names:

| Student | Age | Marks |
|---|---:|---:|
| A | 20 | 75 |
| B | 21 | 88 |

The column names tell us what each value represents.

### Real-World Example

In an online retail dataset, Quantity represents the number of items, Price represents the unit price, and Country represents the customer's country.

### Business Example

A business can use column names to locate the information required for sales reports and product analysis.

### AI/ML Use Case

Column names help data analysts select suitable input features and identify a possible target variable based on the prediction problem.

### Importance in Data Analysis

Checking column names helps us confirm that the expected information is available before performing calculations or visualizations.

In [7]:

# Display all column names
column_names = df.columns.tolist()

print("Total Number of Columns:", len(column_names))
print("\nColumn Names:")

for column in column_names:
    print(column)

Total Number of Columns: 8

Column Names:
Invoice
StockCode
Description
Quantity
InvoiceDate
Price
Customer ID
Country


## Code Explanation

### 1. `df.columns`

This returns all column labels in the DataFrame.

### 2. `.tolist()`

This converts the column labels into a Python list and stores them in `column_names`.

### 3. `len(column_names)`

This counts the number of column names in the list. It helps us verify how many columns are present.

### 4. `for column in column_names:`

This loop processes each column name one at a time.

### 5. `print(column)`

This displays each column name on a separate line, making the output easy to read.

### What Does the Output Tell Us?

The output displays the total number of columns and their names. The names should match the information expected from the dataset.

### Insights We Can Obtain

- Verify the available columns.
- Identify unexpected or misspelled names.
- Find the correct column names to use in later code.
- Check whether important business information is available.

### Impact on the ML Pipeline

Correct column names help us select input features, prepare the target variable, and write reliable data-processing code. If column names contain spaces or unexpected characters, we must use them correctly when accessing the data.


# Topic 5: Index
## Step 1: Understand the Concept

### What Is an Index?

An index is a label used to identify and access rows in a Pandas DataFrame. By default, Pandas assigns integer labels starting from 0.

### Why Is an Index Important?

- It helps identify and access specific rows.
- It allows us to select records during data analysis.
- It helps us understand how rows are labeled.
- It can be used to align data when combining or comparing DataFrames.

### Important Note

The index is not usually considered a feature or column in the dataset. However, a DataFrame can have a custom index, and an index can sometimes be meaningful depending on the dataset.

**Conclusion:** Understanding the index helps us select and work with DataFrame rows correctly.


## Step 2: Demonstrate the Concept

### Simple Example

Consider this student dataset:

| Index | Student | Marks |
|---:|---|---:|
| 0 | A | 75 |
| 1 | B | 88 |
| 2 | C | 92 |

The index labels each row as 0, 1, and 2.

### Real-World Example

In an online retail dataset, the index can help us locate a particular transaction record.

### Business Example

An analyst can use row indexes to inspect unusual sales records and investigate possible data-quality issues.

### AI/ML Use Case

Indexes help keep records aligned when preparing features and target values. Before model training, the index should be checked if datasets are filtered, sorted, or combined.

### Importance in Data Analysis

Inspecting the index helps us understand row labels and avoid confusion between the index and actual dataset columns.

In [8]:

# Display the index of the dataset
print("Dataset Index:")
print(df.index)

# Display the first five index labels
print("\nFirst Five Index Labels:")
print(df.index[:5])

# Check whether the index is unique
print("\nIs the Index Unique?")
print(df.index.is_unique)

# Display the first five records with their index
print("\nFirst Five Records:")
display(df.head())

Dataset Index:
RangeIndex(start=0, stop=525461, step=1)

First Five Index Labels:
RangeIndex(start=0, stop=5, step=1)

Is the Index Unique?
True

First Five Records:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom


## Code Explanation

### 1. `df.index`

This returns the index object containing the row labels of the DataFrame. A default DataFrame commonly uses a range of integer labels.

### 2. `df.index[:5]`

This selects the first five index labels using slicing. It helps us inspect how the rows are labeled at the beginning of the dataset.

### 3. `df.index.is_unique`

This returns `True` if every index label is unique and `False` if any label is repeated.

A unique index does not guarantee that the dataset contains no duplicate records. Two rows can contain identical values while having different index labels.

### 4. `df.head()`

This displays the first five rows along with their index labels, allowing us to view the index and the dataset columns together.

### What Does the Output Tell Us?

The output shows the index structure, its first five labels, whether those labels are unique, and how they appear beside the records.

### Insights We Can Obtain

- Understand the row-label format.
- Check whether index labels are unique.
- Distinguish the index from actual data columns.
- Identify situations where index alignment may matter.

### Impact on the ML Pipeline

Correct index handling helps maintain the alignment between input features and target values. After sorting, filtering, or merging data, we should verify that the correct records remain aligned.


# Topic 6: head()
## Step 1: Understand the Concept

### What Is head()?

The `head()` method is a Pandas method used to display the first few rows of a DataFrame.

By default, `df.head()` displays the first five rows. We can specify a number inside the parentheses to display a different number of rows.

### Why Is head() Important?

- It helps us preview the dataset.
- It allows us to check whether the data has loaded correctly.
- It helps us inspect column names and sample values.
- It provides an initial view of the dataset before detailed analysis.

**Conclusion:** The `head()` method is one of the simplest ways to inspect the beginning of a dataset.


## Step 2: Demonstrate the Concept

### Simple Example

Consider a dataset containing 100 student records.

- `df.head()` displays the first 5 records.
- `df.head(3)` displays the first 3 records.
- `df.head(10)` displays the first 10 records.

### Real-World Example

In the Online Retail II dataset, `head()` can display the first few invoice and product transaction records.

### Business Example

A sales analyst can preview product descriptions, quantities, prices, and countries to check whether the data looks reasonable.

### AI/ML Use Case

Before preparing features for a machine learning model, an analyst can preview the dataset to understand its structure and notice obvious data issues.

### Importance in Data Analysis

Previewing the first few rows helps us confirm that the correct dataset is loaded and prepares us for further inspection.

In [9]:

# Display the first five rows
print("First Five Rows:")
display(df.head())

# Display the first ten rows
print("\nFirst Ten Rows:")
display(df.head(10))

First Five Rows:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

First Ten Rows:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom


## Code Explanation

### 1. `df.head()`

The `head()` method returns the first five rows by default. It is useful for getting a quick preview of the dataset.

### 2. `df.head(10)`

The number `10` specifies how many rows to display. This statement returns the first ten rows instead of the default five.

### 3. `display()`

The `display()` function presents the returned rows in a readable table format in Jupyter Notebook.

### 4. `print()`

The `print()` function displays a heading before each table so that the outputs are easier to distinguish.

### What Does the Output Tell Us?

The first table contains up to five rows, and the second contains up to ten rows. If the dataset has fewer rows than requested, Pandas displays only the available rows.

### Insights We Can Obtain

- Check whether the dataset was loaded correctly.
- Review the first records and their column values.
- Notice obvious missing or unusual values.
- Understand how the information is arranged.

### Impact on the ML Pipeline

The `head()` method supports initial data inspection before cleaning and feature engineering. However, the first few rows may not represent the entire dataset, so other inspection methods are also necessary.


# Topic 7: tail()
## Step 1: Understand the Concept

### What Is tail()?

The `tail()` method is a Pandas method used to display the last few rows of a DataFrame.

By default, `df.tail()` displays the last five rows. We can specify a number inside the parentheses to display a different number of rows.

### Why Is tail() Important?

- It helps us inspect the end of a dataset.
- It allows us to check the final records after loading data.
- It helps identify unusual or missing values near the end of the dataset.
- It is useful for checking data after sorting or processing.

**Conclusion:** The `tail()` method helps us inspect the last records and understand how the dataset ends.


## Step 2: Demonstrate the Concept

### Simple Example

Consider a dataset containing 100 student records.

- `df.tail()` displays the last 5 records.
- `df.tail(3)` displays the last 3 records.
- `df.tail(10)` displays the last 10 records.

### Real-World Example

In the Online Retail II dataset, `tail()` displays the final transaction records available in the loaded worksheet.

### Business Example

A sales analyst can inspect the final records to check whether the latest rows contain expected transaction details or unusual values.

### AI/ML Use Case

After data processing, `tail()` can help verify that records remain present and that the final rows look reasonable.

### Importance in Data Analysis

Using `head()` and `tail()` together gives us a quick preview of both ends of a dataset. However, they do not guarantee that every row is correct.

In [10]:

# Display the last five rows
print("Last Five Rows:")
display(df.tail())

# Display the last ten rows
print("\nLast Ten Rows:")
display(df.tail(10))

Last Five Rows:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom

Last Ten Rows:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
525451,538171,22748,POPPY'S PLAYHOUSE KITCHEN,2,2010-12-09 20:01:00,2.10,17530.0,United Kingdom
525452,538171,22745,POPPY'S PLAYHOUSE BEDROOM,2,2010-12-09 20:01:00,2.10,17530.0,United Kingdom
525453,538171,22558,CLOTHES PEGS RETROSPOT PACK 24,4,2010-12-09 20:01:00,1.49,17530.0,United Kingdom
525454,538171,21671,RED SPOT CERAMIC DRAWER KNOB,6,2010-12-09 20:01:00,1.25,17530.0,United Kingdom
525455,538171,20971,PINK BLUE FELT CRAFT TRINKET BOX,2,2010-12-09 20:01:00,1.25,17530.0,United Kingdom
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom


## Code Explanation

### 1. `df.tail()`

The `tail()` method returns the last five rows of the DataFrame by default.

### 2. `df.tail(10)`

The value `10` specifies the number of rows to display from the end of the DataFrame.

### 3. `display()`

The `display()` function shows the returned rows in a readable table format in Jupyter Notebook.

### 4. `print()`

The `print()` function displays a heading before each output, making the two tables easier to identify.

### What Does the Output Tell Us?

The first table displays up to five rows from the end of the dataset. The second displays up to ten rows from the end.

If fewer rows are available than requested, Pandas displays only the rows that exist.

### Insights We Can Obtain

- Inspect the final records.
- Check whether the loaded data appears complete at the end.
- Notice unusual or missing values in the displayed records.
- Verify the result of data-processing operations.

### Impact on the ML Pipeline

The `tail()` method supports data inspection after loading, sorting, filtering, or transforming data. It should be combined with other checks because the final rows alone may not represent the entire dataset.


# Topic 8: sample()
## Step 1: Understand the Concept

### What Is sample()?

The `sample()` method is a Pandas method used to select random rows from a DataFrame.

By default, `df.sample()` selects one random row. We can specify the number of rows to select by passing a value inside the parentheses.

### Why Is sample() Important?

- It helps us inspect records from different parts of the dataset.
- It provides a quick way to examine randomly selected records.
- It may help us notice unusual values that are not visible in the first or last rows.
- It is useful for an initial review of large datasets.

**Conclusion:** The `sample()` method provides a random preview of the dataset, complementing `head()` and `tail()`.


## Step 2: Demonstrate the Concept

### Simple Example

Consider a dataset containing 100 student records.

- `df.sample()` selects one random record.
- `df.sample(5)` selects five random records.
- `df.sample(10)` selects ten random records.

### Real-World Example

In the Online Retail II dataset, random sampling can show transactions from different positions in the loaded data.

### Business Example

A business analyst can randomly inspect transaction records to review product descriptions, quantities, prices, and countries.

### AI/ML Use Case

Sampling can help analysts examine representative-looking records before building a model. However, a random sample is not guaranteed to represent every category or rare event.

### Importance in Data Analysis

Random sampling provides a broader initial preview than inspecting only the first or last rows. For repeatable results, we can use a fixed `random_state`.

In [11]:

# Select one random row
print("One Random Row:")
display(df.sample())

# Select five random rows
print("\nFive Random Rows:")
display(df.sample(n=5, random_state=42))

One Random Row:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
415046,529068,85038,6 CHOCOLATE LOVE HEART T-LIGHTS,1,2010-10-26 12:14:00,4.21,NaN,United Kingdom

Five Random Rows:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
391453,527050,20750,RED RETROSPOT MINI CASES,6,2010-10-14 12:54:00,7.95,17717.0,United Kingdom
440086,531382,82583,HOT BATHS METAL SIGN,3,2010-11-07 16:29:00,2.10,16549.0,United Kingdom
369036,525059,22951,72 CAKE CASES DOLLY GIRL DESIGN,48,2010-10-03 14:08:00,0.55,15978.0,United Kingdom
232578,511928,21915,RED HARMONICA IN BOX,12,2010-06-11 11:45:00,1.25,15141.0,United Kingdom
41357,492792,22311,OFFICE MUG WARMER BLACK+SILVER,12,2009-12-20 10:08:00,4.95,17243.0,United Kingdom


## Code Explanation

### 1. `df.sample()`

This method randomly selects one row from the DataFrame by default.

### 2. `df.sample(n=5, random_state=42)`

- `n=5` requests five rows.
- `random_state=42` makes the selection reproducible when the dataset and its row ordering remain unchanged.

The number 42 is an arbitrary seed value; it has no special statistical meaning.

### 3. `display()`

The `display()` function presents the selected rows in a readable table format.

### What Does the Output Tell Us?

The output displays randomly selected transaction records. Running the first statement again may return a different row. The second statement should return the same sample when the underlying data and row order are unchanged.

### Insights We Can Obtain

- Inspect records from different parts of the dataset.
- Notice unusual quantities, prices, or missing values.
- Review examples without displaying thousands of rows.

### Impact on the ML Pipeline

Sampling helps with exploratory inspection and can support later sampling strategies. For model evaluation, sampling must be designed carefully to avoid biased results or data leakage. A small random sample alone cannot confirm the overall quality of a dataset.


# Topic 9: shape
## Step 1: Understand the Concept

### What Is shape?

The `shape` attribute returns the dimensions of a Pandas DataFrame as a tuple containing two values: the number of rows and the number of columns.

The first value represents rows, and the second value represents columns.

### Why Is shape Important?

- It helps us understand the size of a dataset.
- It provides the row and column counts together.
- It helps verify the dataset after loading, filtering, or cleaning.
- It helps us check whether data-processing operations changed the dataset dimensions.

**Conclusion:** The `shape` attribute provides a quick summary of a DataFrame's dimensions.


## Step 2: Demonstrate the Concept

### Simple Example

Consider a student dataset containing 3 rows and 2 columns.

Its shape is `(3, 2)`.

- `3` represents the number of rows.
- `2` represents the number of columns.

### Real-World Example

The Online Retail II dataset contains transaction records and columns describing invoices, products, quantities, prices, dates, and countries.

### Business Example

A business analyst can check the dataset dimensions before preparing a sales report or filtering records.

### AI/ML Use Case

Before training a model, an analyst can inspect the number of records and features available for analysis.

### Importance in Data Analysis

Checking `shape` helps us understand the dataset size and verify how filtering or cleaning operations affect its dimensions.

In [12]:

# Display the dataset dimensions
print("Dataset Shape:", df.shape)

# Extract the number of rows and columns
number_of_rows = df.shape[0]
number_of_columns = df.shape[1]

print("\nNumber of Rows:", number_of_rows)
print("Number of Columns:", number_of_columns)

Dataset Shape: (525461, 8)

Number of Rows: 525461
Number of Columns: 8


## Code Explanation

### 1. `df.shape`

The `shape` attribute returns a tuple containing the DataFrame dimensions in this order: `(rows, columns)`.

For example, `(1000, 8)` means the DataFrame contains 1,000 rows and 8 columns.

### 2. `df.shape[0]`

Python uses zero-based indexing. Position `0` refers to the first value in the tuple, which represents the number of rows.

### 3. `df.shape[1]`

Position `1` refers to the second value in the tuple, which represents the number of columns.

### 4. Storing the Values

The row and column counts are stored in separate variables so that they can be reused in later calculations or reports.

### What Does the Output Tell Us?

The output shows the total dimensions of the currently loaded DataFrame. The actual values depend on the data in `df`.

### Insights We Can Obtain

- Understand the dataset size.
- Verify that the expected data is loaded.
- Check whether filtering or cleaning changes the row count.
- Monitor changes to the number of columns during feature engineering.

### Impact on the ML Pipeline

Dataset dimensions help us track the amount of data and the number of available features before model preparation. We should also check data quality and feature relevance because dimensions alone do not guarantee that the dataset is suitable for machine learning.


# Topic 10: info()
## Step 1: Understand the Concept

### What Is info()?

The `info()` method provides a summary of a Pandas DataFrame. It displays information about the index, column names, number of non-null values, data types, and memory usage.

### Why Is info() Important?

- It helps us understand the structure of a dataset.
- It shows the data type of each column.
- It helps us identify columns that may contain missing values.
- It provides an overview of memory usage.
- It supports the initial data inspection process.

**Conclusion:** The `info()` method is useful for quickly understanding a DataFrame's structure and identifying areas that need further investigation.


## Step 2: Demonstrate the Concept

### Simple Example

Consider a dataset with three columns: Student, Age, and Marks.

If the Age column contains only two non-null values across three rows, one value may be missing.

### Real-World Example

The Online Retail II dataset contains transaction details such as invoice numbers, product descriptions, quantities, prices, dates, and customer IDs.

### Business Example

A sales analyst can inspect the data types and non-null counts to identify columns that may need cleaning before preparing reports.

### AI/ML Use Case

Before preparing model features, an analyst can check whether columns have missing values or unsuitable data types.

### Importance in Data Analysis

The `info()` method provides a quick overview of the dataset. Additional methods may be needed to count missing values and investigate their causes.

In [13]:

# Display a summary of the dataset
print("Dataset Information:")
df.info()

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[us]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 38.8+ MB


## Code Explanation

### 1. `df.info()`

This method prints a concise summary of the DataFrame.

### 2. Index Information

The output shows the index range or index details, helping us understand how the rows are labeled.

### 3. Column Information

The output lists the column names and the number of non-null values in each column.

### 4. Non-Null Count

The non-null count represents the number of values that are not missing in a column.

If the total row count is 1,000 and a column has 900 non-null values, then 100 values are missing in that column.

### 5. Dtype

The `Dtype` section shows how Pandas stores each column, such as integer, floating-point, or object data.

### 6. Memory Usage

The output estimates how much memory the DataFrame uses. This can be useful when working with large datasets.

### What Does the Output Tell Us?

The output provides a summary of the dataset structure, column data types, non-null counts, and memory usage. A low non-null count compared with the total row count may indicate missing values.

### Insights We Can Obtain

- Identify columns that may contain missing values.
- Review the current data types.
- Understand the dataset's structure.
- Check the approximate memory usage.

### Impact on the ML Pipeline

The information from `info()` helps us plan missing-value handling, data type conversion, and feature preparation. Missing values should be investigated and handled appropriately before model training.


# Topic 11: describe()
## Step 1: Understand the Concept

### What Is describe()?

The `describe()` method generates descriptive statistics for a DataFrame. By default, it summarizes numerical columns and provides information such as count, mean, standard deviation, minimum, quartiles, and maximum.

### Common Statistics

- **Count:** Number of non-missing values.
- **Mean:** Average value.
- **Standard deviation:** How spread out the values are.
- **Minimum:** Smallest value.
- **25%:** First quartile.
- **50%:** Median or second quartile.
- **75%:** Third quartile.
- **Maximum:** Largest value.

### Why Is describe() Important?

- It helps us understand numerical data.
- It provides a quick statistical summary.
- It can reveal unusually large or small values that need investigation.
- It supports the initial exploratory data analysis process.

**Conclusion:** The `describe()` method helps us summarize numerical data and identify values that may need further investigation.


## Step 2: Demonstrate the Concept

### Simple Example

Consider these student marks: 60, 70, 80, 90, and 100.

Descriptive statistics can show the average mark, minimum mark, maximum mark, and the distribution of the values.

### Real-World Example

In the Online Retail II dataset, `describe()` can summarize columns such as Quantity and Price.

### Business Example

A business analyst can use descriptive statistics to understand typical product quantities and unit prices and investigate unusually high or low values.

### AI/ML Use Case

Descriptive statistics help analysts understand feature ranges and variation before data cleaning, scaling, and model preparation.

### Importance in Data Analysis

A statistical summary helps us understand numerical distributions. However, unusual values should be investigated in context rather than automatically removed.

In [14]:

# Generate descriptive statistics for numerical columns
print("Descriptive Statistics:")
display(df.describe())

# Generate descriptive statistics for all columns
print("\nDescriptive Statistics for All Columns:")
display(df.describe(include="all"))

Descriptive Statistics:

            Quantity                 InvoiceDate          Price    Customer ID
count  525461.000000                      525461  525461.000000  417534.000000
mean       10.337667  2010-06-28 11:37:36.845018       4.688834   15360.645478
min     -9600.000000         2009-12-01 07:45:00  -53594.360000   12346.000000
25%         1.000000         2010-03-21 12:20:00       1.250000   13983.000000
50%         3.000000         2010-07-06 09:51:00       2.100000   15311.000000
75%        10.000000         2010-10-15 12:45:00       4.210000   16799.000000
max     19152.000000         2010-12-09 20:01:00   25111.090000   18287.000000
std       107.424110                         NaN     146.126914    1680.811316

Descriptive Statistics for All Columns:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
count,525461.0,525461,522533,525461.000000,525461,525461.000000,417534.000000,525461
unique,28816.0,4632,4681,NaN,NaN,NaN,NaN,40
top,537434.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,United Kingdom
freq,675.0,3516,3549,NaN,NaN,NaN,NaN,485852
mean,NaN,NaN,NaN,10.337667,2010-06-28 11:37:36.845018,4.688834,15360.645478,NaN
min,NaN,NaN,NaN,-9600.000000,2009-12-01 07:45:00,-53594.360000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,2010-03-21 12:20:00,1.250000,13983.000000,NaN
50%,NaN,NaN,NaN,3.000000,2010-07-06 09:51:00,2.100000,15311.000000,NaN
75%,NaN,NaN,NaN,10.000000,2010-10-15 12:45:00,4.210000,16799.000000,NaN
max,NaN,NaN,NaN,19152.000000,2010-12-09 20:01:00,25111.090000,18287.000000,NaN
std,NaN,NaN,NaN,107.424110,NaN,146.126914,1680.811316,NaN


## Code Explanation

### 1. `df.describe()`

This method generates descriptive statistics for numerical columns by default.

### 2. `count`

Shows the number of non-missing values in each summarized column. If the count is lower than the total number of rows, some values may be missing.

### 3. `mean`

Shows the arithmetic average of the values in a column.

### 4. `std`

Shows the standard deviation, which describes the spread of values around the mean.

### 5. `min` and `max`

Show the smallest and largest values in each numerical column.

### 6. `25%`, `50%`, and `75%`

These are quartiles. The 50% value is the median. Quartiles help us understand the distribution of values.

### 7. `df.describe(include="all")`

This requests summaries for all column types. Numerical columns show statistics such as mean and standard deviation, while text or categorical columns may show count, unique values, the most frequent value, and its frequency. Not every statistic applies to every data type.

### What Does the Output Tell Us?

The first table summarizes numerical columns. The second includes summaries for other supported data types as well. Missing values are excluded from many of these calculations.

### Insights We Can Obtain

- Understand typical values and ranges.
- Compare means and medians.
- Identify unusually high or low values for further investigation.
- Check the non-missing count in summarized columns.

### Impact on the ML Pipeline

Descriptive statistics help guide data cleaning and feature preparation. They can indicate whether scaling, transformation, or further investigation of outliers may be useful. The correct action depends on the meaning of the data and the chosen model.


# Topic 12: dtypes
## Step 1: Understand the Concept

### What Is dtypes?

The `dtypes` attribute returns the data type of each column in a Pandas DataFrame.

Common data types include:

- **int64:** Integer values.
- **float64:** Decimal values.
- **object:** Often used for text or mixed values.
- **bool:** True or False values.
- **datetime64:** Date and time values.

### Why Is dtypes Important?

- It helps us identify how each column is stored.
- It helps detect columns that may require type conversion.
- It supports numerical and categorical column identification.
- It helps prepare data for analysis and machine learning.

**Conclusion:** The `dtypes` attribute provides a quick way to inspect the stored data type of every column.


## Step 2: Demonstrate the Concept

### Simple Example

Consider these columns:

| Quantity | Price | Country |
|---:|---:|---|
| 5 | 10.50 | India |
| 3 | 20.00 | Japan |

Quantity may be stored as an integer, Price as a floating-point number, and Country as text.

### Real-World Example

The Online Retail II dataset contains quantities, prices, invoice dates, product descriptions, and country names.

### Business Example

A sales analyst can check whether quantities and prices are stored numerically and whether date columns are stored in a suitable date/time format.

### AI/ML Use Case

Before building a machine learning model, analysts inspect data types to determine which columns need conversion or encoding.

### Importance in Data Analysis

Correct data types help us perform appropriate calculations, inspect categories, analyze dates, and prepare reliable features.

In [15]:

# Display the data type of each column
print("Column Data Types:")
display(df.dtypes)

# Count the number of columns for each data type
print("\nCount of Each Data Type:")
display(df.dtypes.value_counts())

Column Data Types:

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID           float64
Country                   str
dtype: object

Count of Each Data Type:

object            3
float64           2
int64             1
datetime64[us]    1
str               1
Name: count, dtype: int64


## Code Explanation

### 1. `df.dtypes`

The `dtypes` attribute returns a Pandas Series containing each column name and its stored data type.

### 2. `display(df.dtypes)`

This displays the column names alongside their data types, making it easier to inspect the entire DataFrame.

### 3. `df.dtypes.value_counts()`

The `value_counts()` method counts how many columns have each data type.

For example, if five columns have the `object` data type, the summary will show `object` with a count of five.

### What Does the Output Tell Us?

The first output shows the stored data type of each column. The second output summarizes how many columns use each data type.

A column's stored type does not always describe its business meaning. For example, an invoice number may be stored as an integer or text, but it functions as an identifier.

### Insights We Can Obtain

- Identify numerical and text-stored columns.
- Check whether date columns require conversion.
- Understand the distribution of data types across columns.
- Find columns that may need additional inspection.

### Impact on the ML Pipeline

Data type inspection helps us plan data conversion, categorical encoding, date feature extraction, and numerical feature preparation. Before changing a data type, we should verify the meaning of the column and the values it contains.


# Topic 13: nunique()
## Step 1: Understand the Concept

### What Is nunique()?

The `nunique()` method counts the number of distinct values in a Pandas Series or in each column of a DataFrame.

By default, missing values are not included in the count.

### Why Is nunique() Important?

- It helps us understand how many different values exist in a column.
- It helps identify columns with many or few distinct values.
- It helps inspect categorical features and identifier columns.
- It supports initial data-quality checks.

**Conclusion:** The `nunique()` method helps us measure the variety of values in a dataset.


## Step 2: Demonstrate the Concept

### Simple Example

Consider the following Country values:

| Country |
|---|
| India |
| Japan |
| India |
| USA |

There are four records but only three distinct country values.

### Real-World Example

In the Online Retail II dataset, `nunique()` can count the distinct countries, product codes, invoice numbers, and customer IDs.

### Business Example

A business can estimate how many different products or customers appear in its transaction records.

### AI/ML Use Case

Distinct-value counts help analysts understand categorical features and identify high-cardinality columns, such as product codes or customer identifiers.

### Importance in Data Analysis

Unique-value counts help us understand the variety of values in each column. However, high or low cardinality alone does not determine whether a column should be used in a model.

In [16]:

# Count distinct values in each column
print("Distinct Values in Each Column:")
display(df.nunique())

# Count distinct values in selected columns
selected_columns = ["Country", "StockCode", "Invoice", "Customer ID"]

print("\nDistinct Values in Selected Columns:")
display(df[selected_columns].nunique())

# Count distinct values including missing values
print("\nDistinct Customer ID Values Including Missing Values:")
print(df["Customer ID"].nunique(dropna=False))

Distinct Values in Each Column:

Invoice        28816
StockCode       4632
Description     4681
Quantity         825
InvoiceDate    25296
Price           1606
Customer ID     4383
Country           40
dtype: int64

Distinct Values in Selected Columns:

Country           40
StockCode       4632
Invoice        28816
Customer ID     4383
dtype: int64

Distinct Customer ID Values Including Missing Values:
4384


## Code Explanation

### 1. `df.nunique()`

This counts the number of distinct non-missing values in each column of the DataFrame.

### 2. `selected_columns`

This list stores the names of the columns we want to inspect individually.

### 3. `df[selected_columns]`

This selects only the specified columns from the DataFrame.

### 4. `df[selected_columns].nunique()`

This calculates the distinct-value count for each selected column.

### 5. `df["Customer ID"].nunique(dropna=False)`

By default, `nunique()` excludes missing values. Setting `dropna=False` includes missing values as a distinct category in the count.

### What Does the Output Tell Us?

The output shows how many distinct values appear in each column. For example, a country column may have relatively few distinct values, while an invoice or product-code column may have many.

### Insights We Can Obtain

- Understand the variety of values in each column.
- Identify categorical columns with a limited number of categories.
- Identify high-cardinality columns that may need special handling.
- Understand whether missing values affect the distinct-value count.

### Impact on the ML Pipeline

Distinct-value counts help guide categorical encoding and feature selection. Columns with many unique values, such as identifiers, need careful evaluation before being used as model inputs. We should consider their meaning and predictive value rather than relying on the count alone.


# Topic 14: value_counts()
## Step 1: Understand the Concept

### What Is value_counts()?

The `value_counts()` method counts how many times each distinct value appears in a Pandas Series.

By default, the result is sorted from the most frequent value to the least frequent value. Missing values are excluded unless `dropna=False` is specified.

### Why Is value_counts() Important?

- It helps us understand how frequently values occur.
- It helps identify the most common categories.
- It helps inspect categorical features.
- It can reveal unusual or unexpected values.
- It supports exploratory data analysis.

**Conclusion:** The `value_counts()` method helps us understand the frequency and distribution of values in a column.


## Step 2: Demonstrate the Concept

### Simple Example

Consider these country values:

| Country |
|---|
| India |
| Japan |
| India |
| USA |
| India |
| Japan |

The frequency counts are:

| Country | Count |
|---|---:|
| India | 3 |
| Japan | 2 |
| USA | 1 |

### Real-World Example

In the Online Retail II dataset, `value_counts()` can show how frequently each country or product description appears.

### Business Example

A business can identify countries with the highest number of transaction lines or products that appear most frequently in the dataset.

### AI/ML Use Case

Frequency counts help analysts understand category distributions and identify rare categories that may need special handling before model training.

### Importance in Data Analysis

Frequency analysis helps us understand which values are common, which are rare, and whether some categories need further investigation.

In [17]:

# Count transaction records by country
print("Top 10 Countries by Record Count:")
display(df["Country"].value_counts().head(10))

# Count the most frequent product descriptions
print("\nTop 10 Product Descriptions:")
display(df["Description"].value_counts().head(10))

# Count values including missing country values
print("\nCountry Counts Including Missing Values:")
display(df["Country"].value_counts(dropna=False).head(10))

Top 10 Countries by Record Count:

Country
United Kingdom     485852
EIRE                 9670
Germany              8129
France               5772
Netherlands          2769
Spain                1278
Switzerland          1187
Portugal             1101
Belgium              1054
Channel Islands       906
Name: count, dtype: int64

Top 10 Product Descriptions:

Description
WHITE HANGING HEART T-LIGHT HOLDER    3549
REGENCY CAKESTAND 3 TIER              2212
STRAWBERRY CERAMIC TRINKET BOX        1843
PACK OF 72 RETRO SPOT CAKE CASES      1466
ASSORTED COLOUR BIRD ORNAMENT         1457
60 TEATIME FAIRY CAKE CASES           1400
HOME BUILDING BLOCK WORD              1386
JUMBO BAG RED RETROSPOT               1310
LUNCH BAG RED SPOTTY                  1274
REX CASH+CARRY JUMBO SHOPPER          1232
Name: count, dtype: int64

Country Counts Including Missing Values:

Country
United Kingdom     485852
EIRE                 9670
Germany              8129
France               5772
Netherlands          2769
Spain                1278
Switzerland          1187
Portugal             1101
Belgium              1054
Channel Islands       906
Name: count, dtype: int64


## Code Explanation

### 1. `df["Country"]`

This selects the Country column from the DataFrame as a Pandas Series.

### 2. `value_counts()`

This counts how many times each distinct country appears in the selected column. The default result is ordered by frequency, from highest to lowest.

### 3. `head(10)`

This displays only the first ten entries of the frequency table. It helps us focus on the most frequent values.

### 4. `df["Description"].value_counts()`

This counts how frequently each product description appears in the transaction records.

### 5. `value_counts(dropna=False)`

By default, missing values are excluded. Setting `dropna=False` includes missing values in the frequency counts.

### What Does the Output Tell Us?

The output shows the most frequent countries and product descriptions based on transaction-row counts. It also helps us see whether missing country values exist.

### Insights We Can Obtain

- Identify countries with the highest transaction-row counts.
- Find frequently appearing product descriptions.
- Detect missing or rare categories.
- Understand the distribution of categorical values.

### Impact on the ML Pipeline

Frequency counts help guide category handling, encoding, and data-quality checks. Before drawing business conclusions, remember that frequent transaction rows do not necessarily mean higher sales revenue or more unique customers.