In [1]:
import pandas as pd
import numpy as np

file_path = "online_retail_II.xlsx"
df = pd.read_excel(file_path, sheet_name="Year 2009-2010")

print("Dataset loaded successfully!")
display(df.head())

Dataset loaded successfully!

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

# Missing Values

## Topic 1: Number of Missing Values

### Step 1: Understand the Concept

Missing values are values that are not available or recorded in a dataset. In Python, they are commonly represented as `NaN`, `None`, or `NaT`, depending on the data type.

Identifying missing values is the first step in assessing data quality. Missing information can affect calculations, visualizations, statistical analysis, and machine learning models.

**Why do we check missing values?**

- To understand how much information is missing from the dataset.
- To identify incomplete records.
- To decide whether missing values should be removed, filled, or investigated.
- To improve the reliability of data analysis and machine learning results.

**Important:** Missing values should not be removed automatically. The correct approach depends on the column, the reason for missing data, and the business problem.

## Step 2: Demonstrate the Concept

**Simple Example**

Consider a dataset containing customer information:

| Customer | Age | City |
|---|---:|---|
| A | 25 | Chennai |
| B | NaN | Madurai |
| C | 30 | NaN |
| D | NaN | Coimbatore |

There are three missing values in this example: two in the Age column and one in the City column.

**Real-World Example**

In an online shopping dataset, a transaction may have a missing product description or customer ID.

**Business Example**

If customer information is missing, a business may find it difficult to understand customer purchasing behaviour.

**AI/ML Use Case**

Missing values can cause errors in some machine learning algorithms or reduce model quality if they are not handled appropriately.

**Importance in Data Analysis**

Counting missing values helps us understand how complete the dataset is before moving to deeper analysis.

In [2]:
# Count the total number of missing values in the dataset
total_missing_values = df.isnull().sum().sum()

print("Total Number of Missing Values:", total_missing_values)

Total Number of Missing Values: 110855

## Code Explanation

**1. `df.isnull()`**

Checks every cell in the DataFrame and identifies missing values.

- `True` means the value is missing.
- `False` means the value is present.

**2. `df.isnull().sum()`**

Counts missing values separately for each column because `True` is treated as `1` and `False` as `0` during summation.

**3. `.sum().sum()`**

- The first `.sum()` counts missing values in each column.
- The second `.sum()` adds those column counts together to calculate the total number of missing values in the entire dataset.

**4. `print()`**

Displays the total missing-value count.

**Expected Output**

The output will look like this:

`Total Number of Missing Values: ...`

The actual number depends on the dataset loaded. The ellipsis is a placeholder, not a value to type into your code.

**What does the result mean?**

- If the result is `0`, pandas has not detected any missing values represented as standard null values.
- If the result is greater than `0`, the dataset contains missing values that need further investigation.

**Impact on the ML Pipeline**

This check helps identify whether missing-data handling may be needed during data preprocessing. It does not modify or delete any data.

# Topic 2: Percentage of Missing Values

## Step 1: Understand the Concept

The percentage of missing values tells us what proportion of the dataset's values are missing.

It is calculated by dividing the number of missing values by the total number of values and multiplying the result by 100.

**Formula:**

Missing Value Percentage = (Number of Missing Values / Total Number of Values) × 100

**Why do we calculate it?**

- To measure data completeness.
- To compare missing data across datasets or columns.
- To identify columns with a high percentage of missing values.
- To help decide how missing values should be handled.

A high missing percentage does not automatically mean that a column should be deleted. The decision depends on the column's importance and the business objective.

## Step 2: Demonstrate the Concept

**Simple Example**

Suppose a column contains 100 customer records, and 20 values are missing.

Missing Value Percentage = (20 / 100) × 100 = 20%

This means that 20% of the values in that column are missing.

**Real-World Example**

An online retail dataset may contain 1,000 customer IDs, of which 150 are missing.

**Business Example**

If many customer IDs are missing, the business may have difficulty analysing individual customer purchasing behaviour.

**AI/ML Use Case**

A high percentage of missing values in an important feature may affect model training and may require a suitable preprocessing strategy.

**Importance in Data Analysis**

Percentages help compare columns fairly, especially when interpreting missing data across different fields.

In [3]:
# Calculate the total number of cells in the dataset
total_values = df.size

# Calculate the total number of missing values
total_missing_values = df.isnull().sum().sum()

# Calculate the percentage of missing values
if total_values > 0:
    missing_percentage = (total_missing_values / total_values) * 100
else:
    missing_percentage = 0

print(f"Total Values: {total_values}")
print(f"Missing Values: {total_missing_values}")
print(f"Missing Value Percentage: {missing_percentage:.2f}%")

Total Values: 4203688
Missing Values: 110855
Missing Value Percentage: 2.64%

## Code Explanation

**1. `df.size`**

Returns the total number of cells in the DataFrame, including rows multiplied by columns.

For example, a DataFrame with 100 rows and 5 columns contains 500 cells.

**2. `df.isnull().sum().sum()`**

Counts all missing values across the entire dataset.

**3. `if total_values > 0:`**

Checks that the dataset contains at least one cell before performing the division. This avoids division by zero.

**4. `(total_missing_values / total_values) * 100`**

Calculates the percentage of cells that contain missing values.

**5. `else: missing_percentage = 0`**

If the dataset has no cells, the code assigns zero to the result rather than attempting a division by zero. In that situation, the percentage is only a fallback value and should not be interpreted as evidence of complete data.

**6. `:.2f`**

Formats the percentage to two decimal places.

**7. `print()`**

Displays the total number of cells, the missing-value count, and the calculated percentage.

**What does the output mean?**

- A low percentage indicates that relatively few cells are missing.
- A high percentage indicates that more of the dataset is incomplete.
- A percentage of `0.00%` means no standard missing values were detected in the cells checked.

**Important Note**

This calculation measures missing cells across the entire dataset. In the next topic, we will calculate missing values separately for each column to identify which fields need attention.

**Impact on the ML Pipeline**

This measurement supports data-cleaning decisions before feature preparation and model training. It does not change the original dataset.

# Topic 3: Missing Values by Column

## Step 1: Understand the Concept

Missing values by column means counting the number of missing values separately for every column in a dataset.

Each column may contain a different number of missing values. Some columns may have no missing values, while others may have many.

**Why do we check missing values by column?**

- To identify columns with incomplete information.
- To find which columns require further investigation.
- To compare data completeness across different features.
- To decide whether missing values should be retained, filled, or removed.

**Important:** A column with many missing values is not automatically useless. Its business importance and the reason for the missing data should also be considered.

## Step 2: Demonstrate the Concept

**Simple Example**

Consider the following customer dataset:

| Name | Age | City |
|---|---:|---|
| Arun | 25 | Chennai |
| Priya | NaN | Madurai |
| Ravi | NaN | NaN |
| Meena | 30 | Chennai |

Missing-value counts:

| Column | Missing Values |
|---|---:|
| Name | 0 |
| Age | 2 |
| City | 1 |

**Real-World Example**

In an online retail dataset, customer IDs or product descriptions may be missing in some transaction records.

**Business Example**

If a large number of customer IDs are missing, customer-level purchase analysis may be limited.

**AI/ML Use Case**

A missing-value summary helps identify features that may require imputation or other preprocessing before model training.

**Importance in Data Analysis**

Column-wise counts show exactly where the data quality issues occur instead of providing only one overall number.

In [4]:
# Count missing values in each column
missing_by_column = df.isnull().sum()

# Sort columns by missing-value count in descending order
missing_by_column = missing_by_column.sort_values(ascending=False)

print("Missing Values by Column:")
display(missing_by_column.to_frame(name="Missing Count"))

Missing Values by Column:

             Missing Count
Customer ID         107927
Description           2928
StockCode                0
Invoice                  0
Quantity                 0
InvoiceDate              0
Price                    0
Country                  0

## Code Explanation

**1. `df.isnull()`**

Checks every cell and identifies standard missing values.

**2. `.sum()`**

Counts missing values separately for each column.

**3. `missing_by_column = ...`**

Stores the count for each column in a pandas Series. The column names become the Series index, and the values represent missing-value counts.

**4. `.sort_values(ascending=False)`**

Sorts the counts from highest to lowest so columns with the most missing values appear first.

- `ascending=False` means descending order.
- Columns with zero missing values will appear toward the bottom.

**5. `to_frame(name="Missing Count")`**

Converts the Series into a DataFrame and names the resulting column `Missing Count`, making the output easier to read.

**6. `display()`**

Shows the result as a formatted table in Jupyter Notebook.

**What does the output mean?**

Each row shows a column from the retail dataset and its number of missing values. Check which columns have the highest counts and which have zero.

**Important Note**

This code counts missing values but does not change or remove them. It detects standard null values; empty strings and other unusual placeholders may need separate checks.

**Impact on the ML Pipeline**

Column-wise missing-value analysis helps guide preprocessing decisions, including whether a feature needs imputation or further investigation. These decisions should be made based on the data and the intended prediction task.

# Topic 4: Missing Value Patterns

## Step 1: Understand the Concept

Missing value patterns describe how missing values are distributed across rows and columns in a dataset.

They help us understand whether missing values occur independently, appear together in multiple columns, or are concentrated in particular records.

**Common Patterns**

- **Single-column missingness:** Missing values occur mainly in one column.
- **Multiple-column missingness:** Several columns contain missing values in the same rows.
- **Row-level missingness:** Some records contain many missing values.
- **Repeated missingness:** The same combination of columns is missing across multiple records.

**Why do we investigate missing value patterns?**

- To identify repeated data-quality issues.
- To understand which records are incomplete.
- To investigate possible reasons for missing information.
- To choose an appropriate missing-data handling strategy.

**Important:** A missing-value pattern alone does not prove why data is missing or whether the missingness is random. Additional context may be required.

## Step 2: Demonstrate the Concept

**Simple Example**

Consider this customer dataset:

| Customer | Age | City | Income |
|---|---:|---|---:|
| A | 25 | Chennai | 40000 |
| B | NaN | Madurai | 35000 |
| C | NaN | NaN | NaN |
| D | 30 | Chennai | NaN |

In this example:

- Customer B has a missing Age.
- Customer C has missing values in three columns.
- Customer D has a missing Income.

These records show different missing-value patterns.

**Real-World Example**

In online retail data, some transactions may have a missing Customer ID while product and transaction details are available.

**Business Example**

If many records have missing customer information, the business may need to investigate how customer details are captured during transactions.

**AI/ML Use Case**

Understanding missingness patterns helps data scientists select suitable preprocessing methods and avoid blindly deleting useful records.

**Importance in Data Analysis**

Pattern analysis provides more detail than a simple missing-value count and helps identify records that may need closer investigation.

In [5]:
# Create a Boolean mask showing missing values
missing_mask = df.isnull()

# Count missing values in each row
missing_per_row = missing_mask.sum(axis=1)

# Count rows by the number of missing values they contain
print("Number of Rows by Missing-Value Count:")
display(missing_per_row.value_counts().sort_index().to_frame(
    name="Number of Rows"
))

# Show the most common missing-value combinations
print("\nMost Common Missing-Value Patterns:")
display(
    missing_mask.astype(int)
    .value_counts()
    .head(10)
    .to_frame(name="Number of Rows")
)

# Show rows that contain at least one missing value
print("\nSample Rows Containing Missing Values:")
display(df.loc[missing_per_row > 0].head(10))

Number of Rows by Missing-Value Count:

   Number of Rows
0          417534
1          104999
2            2928

Most Common Missing-Value Patterns:

                                                                              Number of Rows
Invoice StockCode Description Quantity InvoiceDate Price Customer ID Country
0       0         0           0        0           0     0           0                417534
                                                         1           0                104999
                  1           0        0           0     1           0                  2928

Sample Rows Containing Missing Values:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.00,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.00,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.00,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.00,NaN,United Kingdom
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom
578,489525,85227,SET/6 3D KIT CARDS FOR KIDS,1,2009-12-01 11:49:00,0.85,NaN,United Kingdom
1055,489548,22271,FELTCRAFT DOLL ROSIE,1,2009-12-01 12:32:00,2.95,NaN,United Kingdom
1056,489548,22254,FELT TOADSTOOL LARGE,12,2009-12-01 12:32:00,1.25,NaN,United Kingdom
1057,489548,22273,FELTCRAFT DOLL MOLLY,3,2009-12-01 12:32:00,2.95,NaN,United Kingdom
1058,489548,22195,LARGE HEART MEASURING SPOONS,1,2009-12-01 12:32:00,1.65,NaN,United Kingdom

## Code Explanation

**1. `df.isnull()`**

Creates a Boolean DataFrame in which `True` represents a missing value and `False` represents a present value.

**2. `missing_mask.sum(axis=1)`**

Counts missing values in each row.

- `axis=1` means the calculation is performed across columns for every row.
- A result of `0` means that row has no standard missing values.
- A result of `3` means that row has three missing values.

**3. `missing_per_row.value_counts()`**

Counts how many rows contain each possible number of missing values.

For example, it may show how many rows have zero, one, two, or more missing values.

**4. `.sort_index()`**

Sorts the row-level missing-value counts in ascending order of the number of missing values.

**5. `missing_mask.astype(int)`**

Converts Boolean values into integers:

- `True` becomes `1`.
- `False` becomes `0`.

This makes each row's missing-value combination easier to count.

**6. `.value_counts().head(10)`**

Counts repeated combinations of missing and present values, then displays the ten most frequent patterns.

Each combination represents the missingness pattern across the dataset's columns. The displayed combination contains `1` for a missing value and `0` for a present value.

**7. `.to_frame(name="Number of Rows")`**

Converts the counts into a DataFrame with a clear column name.

**8. `df.loc[missing_per_row > 0].head(10)`**

Selects rows with at least one missing value and displays up to ten examples for inspection.

**What does the output mean?**

- The first table shows how many rows contain different numbers of missing values.
- The second table shows the most frequent combinations of missing values across columns.
- The third table displays example records that need further investigation.

**Performance Note**

For a large dataset with many columns, counting every distinct missing-value combination can be expensive. Here, `.head(10)` limits the displayed results, but pandas still needs to calculate the combinations before selecting the ten most common.

**Impact on the ML Pipeline**

Missing-value patterns help guide data-cleaning and preprocessing decisions. Investigating the reason for missingness is important before choosing imputation or record-removal methods.

# Duplicate Records

## Topic 5: Identify Duplicates

### Step 1: Understand the Concept

Duplicate records are records that repeat data already present in a dataset.

Identifying duplicates is an important part of data quality assessment because repeated records may affect transaction counts, revenue calculations, and statistical analysis.

**Types of Duplicates**

- **Completely duplicated rows:** Every column has the same value as another row.
- **Potential duplicate records:** Selected columns match, but other columns may differ.

**Why do we identify duplicates?**

- To detect repeated records.
- To investigate possible data-entry or data-import issues.
- To prevent incorrect counts and calculations.
- To decide whether records need further investigation.

**Important:** A repeated record is not always an error. Before removing duplicates, we must understand the dataset and confirm whether the repeated information represents a genuine transaction or an accidental repetition.

## Step 2: Demonstrate the Concept

**Simple Example**

| Invoice | Product | Quantity |
|---|---|---:|
| 1001 | Pen | 2 |
| 1002 | Book | 1 |
| 1001 | Pen | 2 |

The first and third rows contain identical values in all three displayed columns. They would be duplicates if these were the complete columns being checked.

**Real-World Example**

A retail system may import the same transaction record twice because of an import or processing issue.

**Business Example**

Repeated transaction rows may cause a business to overestimate the number of items sold or the value of sales.

**AI/ML Use Case**

Duplicates can introduce unintended weighting into a dataset and influence model training or evaluation.

**Importance in Data Analysis**

Duplicate identification helps us investigate data reliability before performing detailed analysis.

In [6]:
# Identify rows that are duplicates of earlier rows
duplicate_mask = df.duplicated()

# Display whether each row is a duplicate
print("Duplicate Status for the First 10 Rows:")
display(duplicate_mask.head(10).to_frame(name="Is Duplicate"))

# Display sample duplicate records
print("\nSample Duplicate Records:")
display(df.loc[duplicate_mask].head(10))

Duplicate Status for the First 10 Rows:

   Is Duplicate
0         False
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False

Sample Duplicate Records:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom

## Code Explanation

**1. `df.duplicated()`**

Checks whether each row duplicates a row that appeared earlier in the DataFrame.

By default, pandas compares all columns and marks only subsequent occurrences as duplicates.

- `True` means the row has appeared before with the same values in all compared columns.
- `False` means pandas has not found an earlier identical row.

**2. `duplicate_mask`**

Stores the Boolean results so we can reuse them for filtering and analysis.

**3. `duplicate_mask.head(10)`**

Displays the duplicate status for the first ten rows. This is a small preview and does not guarantee that those rows contain duplicates.

**4. `.to_frame(name="Is Duplicate")`**

Converts the Boolean Series into a one-column DataFrame with a clear column name.

**5. `df.loc[duplicate_mask]`**

Selects the rows marked as duplicates.

**6. `.head(10)`**

Displays up to ten duplicate records for inspection.

**What does the output mean?**

If the sample duplicate table is empty, pandas did not find any duplicate rows in the selected result. This does not mean there are no potential duplicates based on only some columns.

**Important Note**

This code identifies completely duplicated rows across all columns. It does not delete or modify any records. We will count the duplicates separately in the next topic.

**Impact on the ML Pipeline**

Identifying duplicate records helps prevent unintended repetition from distorting data summaries or model training. Any removal should happen only after investigating whether the repeated records are truly redundant.

# Topic 6: Count Duplicates

## Step 1: Understand the Concept

Counting duplicates means calculating the total number of rows that repeat an earlier row across all columns.

In pandas, `duplicated()` identifies duplicate occurrences, and `sum()` counts how many rows are marked as duplicates.

**Why do we count duplicates?**

- To measure the number of repeated records.
- To understand the extent of possible duplication in a dataset.
- To support data-cleaning decisions.
- To investigate whether repeated rows may affect business calculations.

**Important:** The duplicate count does not include the first occurrence of a repeated row. It counts only subsequent occurrences by default.

## Step 2: Demonstrate the Concept

**Simple Example**

| Invoice | Product | Quantity |
|---|---|---:|
| 1001 | Pen | 2 |
| 1002 | Book | 1 |
| 1001 | Pen | 2 |
| 1001 | Pen | 2 |

The first occurrence of invoice 1001 is not counted as a duplicate. The second and third occurrences are duplicates.

Therefore, the duplicate count is 2.

**Real-World Example**

An online shopping system may accidentally import a transaction multiple times.

**Business Example**

Duplicate transactions may inflate transaction counts and sales totals if they are included without investigation.

**AI/ML Use Case**

Counting duplicates helps determine whether repeated observations require investigation before training a machine learning model.

**Importance in Data Analysis**

The count gives us a quick measure of repeated records and helps us decide whether further investigation is necessary.

In [7]:
# Count completely duplicated rows
duplicate_count = df.duplicated().sum()

# Calculate the total number of rows
total_rows = len(df)

# Calculate the percentage of duplicate rows
if total_rows > 0:
    duplicate_percentage = (duplicate_count / total_rows) * 100
else:
    duplicate_percentage = 0

print("Total Rows:", total_rows)
print("Duplicate Rows:", duplicate_count)
print(f"Duplicate Row Percentage: {duplicate_percentage:.2f}%")

Total Rows: 525461
Duplicate Rows: 6865
Duplicate Row Percentage: 1.31%

## Code Explanation

**1. `df.duplicated()`**

Checks every row against earlier rows using all columns. Subsequent occurrences of identical rows are marked as `True`.

**2. `.sum()`**

Counts the `True` values to calculate the total number of duplicate rows.

**3. `len(df)`**

Returns the total number of rows in the dataset.

**4. `if total_rows > 0:`**

Checks whether the dataset contains rows before calculating the percentage.

**5. `(duplicate_count / total_rows) * 100`**

Calculates the percentage of rows marked as duplicates relative to the total number of rows.

**6. `else: duplicate_percentage = 0`**

Provides a fallback when the DataFrame has no rows. If the dataset is empty, this zero is not a meaningful measurement of duplicate prevalence.

**7. `print()` and `:.2f`**

Display the results. The formatting `:.2f` shows the percentage to two decimal places.

**What does the output mean?**

- `Total Rows` shows the dataset's row count.
- `Duplicate Rows` shows subsequent rows identical across all columns.
- `Duplicate Row Percentage` shows the proportion of rows marked as duplicates.

A higher percentage indicates more repeated rows, but it does not automatically prove that the records are incorrect.

**Impact on the ML Pipeline**

This metric helps assess whether duplicate observations could influence data analysis or model training. Investigate the business meaning of the rows before deciding whether to remove them.

# Topic 7: Identify Completely Duplicated Rows

## Step 1: Understand the Concept

Completely duplicated rows are rows in which every column value matches a row that appeared earlier in the dataset.

Pandas identifies these rows using `duplicated()` with its default settings, which mark later occurrences as duplicates.

**Why do we identify completely duplicated rows?**

- To inspect repeated records in detail.
- To verify whether records are identical across all columns.
- To investigate possible data-import or data-entry issues.
- To support reliable transaction and sales analysis.

**Important:** A completely duplicated row is not automatically an error. The original data source and business context should be checked before removing any records.

## Step 2: Demonstrate the Concept

**Simple Example**

| Invoice | Product | Quantity | Price |
|---|---|---:|---:|
| 1001 | Pen | 2 | 10 |
| 1002 | Book | 1 | 50 |
| 1001 | Pen | 2 | 10 |

The first and third rows match across all four columns. The third row is a completely duplicated occurrence.

**Real-World Example**

An online retail dataset may contain identical transaction records because the same data was imported more than once.

**Business Example**

Repeated records may inflate the total number of transactions or the calculated sales amount.

**AI/ML Use Case**

Inspecting complete duplicates helps data scientists determine whether repeated observations could unintentionally influence model training.

**Importance in Data Analysis**

Displaying complete duplicates makes it easier to investigate the actual records and decide on the appropriate next step.

In [8]:
# Identify completely duplicated rows
duplicate_mask = df.duplicated()

# Extract the duplicated occurrences
complete_duplicates = df.loc[duplicate_mask].copy()

print("Number of Completely Duplicated Rows:", len(complete_duplicates))

# Display duplicate records
display(complete_duplicates.head(10))

Number of Completely Duplicated Rows: 6865

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom

## Code Explanation

**1. `df.duplicated()`**

Checks all columns in each row and marks subsequent occurrences of identical rows as `True`.

**2. `duplicate_mask`**

Stores the Boolean result so it can be reused to select the matching records.

**3. `df.loc[duplicate_mask]`**

Selects the rows identified as duplicates.

**4. `.copy()`**

Creates a separate copy of the selected rows. This is useful if we later need to investigate or work with the duplicate records independently.

**5. `len(complete_duplicates)`**

Counts how many duplicate rows were extracted.

**6. `display(complete_duplicates.head(10))`**

Displays up to ten duplicate records in the notebook. If more than ten duplicates exist, the remaining records are not shown in this preview.

**What does the output mean?**

The count shows the number of completely duplicated occurrences. The displayed table lets us inspect their invoice details, product information, quantities, prices, and other available columns.

If the table is empty, no duplicate occurrences were found using all columns.

**Important Note**

This code only identifies and displays duplicate records. It does not remove them or modify the original DataFrame.

**Impact on the ML Pipeline**

Inspecting complete duplicates helps determine whether repeated records should be retained, corrected, or removed during data preparation. Decisions should be based on the meaning of the transactions rather than the duplicate flag alone.

# Topic 8: Identify Potential Duplicate Records

## Step 1: Understand the Concept

Potential duplicate records are records that match across selected columns but may differ in other columns.

Unlike completely duplicated rows, potential duplicates are identified using a subset of columns that are meaningful for a particular business problem.

**Why do we identify potential duplicates?**

- To detect records that may represent the same transaction or event.
- To investigate repeated invoice and product combinations.
- To identify possible data-entry or data-processing issues.
- To improve the reliability of transaction-level analysis.

**Important:** There is no universal rule for identifying potential duplicates. The columns used for comparison must be selected according to the dataset structure and business requirements. A matching invoice and product code may be legitimate, so the results must be investigated before changing the data.

## Step 2: Demonstrate the Concept

**Simple Example**

| Invoice | StockCode | Quantity | Price |
|---|---|---:|---:|
| 1001 | P101 | 2 | 10 |
| 1001 | P101 | 3 | 10 |
| 1002 | P102 | 1 | 50 |

The first two records have the same Invoice and StockCode, but their quantities differ.

They are potential duplicates based on the selected columns, but they are not completely duplicated rows.

**Real-World Example**

An online retailer may have multiple records for the same product within one invoice.

**Business Example**

Investigating repeated invoice-product combinations can help identify data-entry issues or understand how transaction lines are recorded.

**AI/ML Use Case**

Potential duplicate checks help analysts investigate repeated observations before creating features or training a model.

**Importance in Data Analysis**

Checking selected columns can reveal suspicious patterns that a full-row duplicate check will not detect.

In [9]:
# Select columns for potential duplicate checking
comparison_columns = ["Invoice", "StockCode"]

# Check that the required columns exist
available_columns = [
    column for column in comparison_columns
    if column in df.columns
]

if len(available_columns) == len(comparison_columns):
    # Identify repeated Invoice and StockCode combinations
    potential_duplicate_mask = df.duplicated(
        subset=comparison_columns,
        keep=False
    )

    # Extract all records belonging to repeated combinations
    potential_duplicates = df.loc[potential_duplicate_mask].copy()

    print("Potential Duplicate Records:",
          len(potential_duplicates))

    display(
        potential_duplicates
        .sort_values(comparison_columns)
        .head(20)
    )
else:
    print("Required comparison columns are not available.")

Potential Duplicate Records: 25399

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
289,489488,22125,UNION JACK HOT WATER BOTTLE,2,2009-12-01 10:59:00,5.95,17238.0,United Kingdom
299,489488,22125,UNION JACK HOT WATER BOTTLE,1,2009-12-01 10:59:00,5.95,17238.0,United Kingdom
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
373,489517,21790,VINTAGE SNAP CARDS,4,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
393,489517,21790,VINTAGE SNAP CARDS,1,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
372,489517,21791,VINTAGE HEADS AND TAILS CARD GAME,6,2009-12-01 11:34:00,1.25,16329.0,United Kingdom
392,489517,21791,VINTAGE HEADS AND TAILS CARD GAME,1,2009-12-01 11:34:00,1.25,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom

## Code Explanation

**1. `comparison_columns = ["Invoice", "StockCode"]`**

Defines the columns used to identify potential duplicates. Records matching on both columns are considered part of a repeated combination.

**2. `available_columns`**

Checks which selected columns actually exist in the DataFrame. This helps prevent an error if a required column is missing.

**3. `if len(available_columns) == len(comparison_columns):`**

Continues the analysis only if all requested columns are available.

**4. `df.duplicated(subset=comparison_columns, keep=False)`**

Checks for repeated combinations using only Invoice and StockCode.

- `subset=comparison_columns` restricts the comparison to the selected columns.
- `keep=False` marks every row belonging to a repeated combination as `True`, including the first occurrence.

**5. `df.loc[potential_duplicate_mask].copy()`**

Extracts all records flagged as potential duplicates into a separate DataFrame.

**6. `len(potential_duplicates)`**

Counts all records belonging to repeated combinations. This is a record count, not the number of distinct duplicate groups.

**7. `.sort_values(comparison_columns)`**

Groups similar Invoice and StockCode combinations together in the displayed results, making them easier to inspect.

**8. `.head(20)`**

Displays up to 20 records for review.

**What does the output mean?**

The table contains records where the same invoice and stock code combination appears more than once. Other fields, such as Quantity or Price, may be different.

These records require investigation; they should not automatically be treated as errors or deleted.

**Impact on the ML Pipeline**

Potential duplicate checks help analysts assess repeated transaction patterns before aggregation, feature engineering, and model training. The correct comparison columns depend on the intended analysis.

# Invalid Values

## Topic 9: Negative Values Where Inappropriate

### Step 1: Understand the Concept

Negative values are numerical values that are less than zero. In data quality assessment, we check whether negative values are valid for a particular column or represent possible data errors.

**Examples in an Online Retail Dataset**

- **Quantity:** Negative quantities may represent returned or cancelled items.
- **Price:** Negative prices may require investigation because ordinary product selling prices are generally expected to be non-negative.
- **Sales Amount:** A negative amount may be valid when representing a refund or return, depending on the calculation method.

**Why do we check negative values?**

- To identify unusual numerical values.
- To distinguish valid business events from possible data errors.
- To prevent incorrect calculations.
- To support reliable data cleaning and analysis.

**Important:** Do not automatically replace negative values with zero or delete the records. First investigate the column's meaning and the business context.

## Step 2: Demonstrate the Concept

**Simple Example**

| Product | Quantity | Price |
|---|---:|---:|
| Pen | 5 | 10 |
| Book | -2 | 50 |
| Bag | 1 | -20 |

- The negative quantity for the book may represent a return.
- The negative price for the bag should be investigated.

**Real-World Example**

An online customer returns two items, so the transaction system may record a negative quantity to represent the return.

**Business Example**

If negative values are not interpreted correctly, sales reports may become misleading. However, removing valid returns can also make the sales figures inaccurate.

**AI/ML Use Case**

Negative-value checks help identify unusual data before feature engineering and model training.

**Importance in Data Analysis**

This check helps separate legitimate business events from suspicious numerical values before making cleaning decisions.

In [10]:
# Check negative quantities
if "Quantity" in df.columns:
    negative_quantity = df[df["Quantity"] < 0]

    print("Rows with Negative Quantity:", len(negative_quantity))
    display(negative_quantity.head(10))

# Check negative prices
if "Price" in df.columns:
    negative_price = df[df["Price"] < 0]

    print("\nRows with Negative Price:", len(negative_price))
    display(negative_price.head(10))

Rows with Negative Quantity: 12326

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
183,C489449,21871,SAVE THE PLANET MUG,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
184,C489449,84946,ANTIQUE SILVER TEA GLASS ETCHED,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
185,C489449,84970S,HANGING HEART ZINC T-LIGHT HOLDER,-24,2009-12-01 10:33:00,0.85,16321.0,Australia
186,C489449,22090,PAPER BUNTING RETRO SPOTS,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
196,C489459,90200A,PURPLE SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom

Rows with Negative Price: 3

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom

## Code Explanation

**1. `if "Quantity" in df.columns:`**

Checks whether the Quantity column exists before performing the analysis.

**2. `df["Quantity"] < 0`**

Compares each quantity with zero and creates a Boolean condition. Rows with negative quantities satisfy the condition.

**3. `df[df["Quantity"] < 0]`**

Filters the DataFrame to select rows with negative quantities.

**4. `len(negative_quantity)`**

Counts the number of rows with negative quantities.

**5. `display(negative_quantity.head(10))`**

Displays up to ten example records for investigation.

**6. The Price check**

The same logic is applied to the Price column to identify negative prices.

**What does the output mean?**

- Negative quantities may represent returns or cancellations and need business-context checks.
- Negative prices should be investigated to understand whether they are valid adjustments or incorrect entries.
- If no records appear, no negative values were found in that column using this condition.

**Important Note**

This code identifies negative values only. It does not decide whether a value is valid or invalid, and it does not modify the dataset.

**Impact on the ML Pipeline**

Investigating negative values helps prevent incorrect assumptions during data cleaning and feature engineering. Valid returns should be handled according to the purpose of the analysis, while confirmed errors can be addressed using an appropriate documented rule.

# Topic 10: Impossible Values

## Step 1: Understand the Concept

Impossible values are values that violate clear logical rules, valid ranges, or business constraints.

These values may occur because of data-entry errors, incorrect calculations, system issues, or invalid data conversions.

**Examples**

- Negative age in a dataset where age must be non-negative.
- A percentage outside its permitted range when the definition requires values between 0 and 100.
- A product price below zero when the business rule does not allow negative prices.
- A quantity of zero in a dataset where every record is expected to represent an actual item movement.

**Why do we check impossible values?**

- To detect logical inconsistencies.
- To identify possible data-entry errors.
- To improve the reliability of calculations.
- To prevent invalid values from misleading analysis or machine learning.

**Important:** Valid ranges depend on the meaning of each column. Do not classify a value as impossible without a justified rule. In retail data, zero quantities and negative prices may require investigation rather than automatic rejection.

## Step 2: Demonstrate the Concept

**Simple Example**

| Product | Quantity | Price |
|---|---:|---:|
| Pen | 5 | 10 |
| Book | 0 | 50 |
| Bag | 2 | -20 |

- The zero quantity should be investigated to understand why the record exists.
- The negative price should be checked against the business rules.
- Neither value should be deleted automatically without understanding its meaning.

**Real-World Example**

A product catalogue may contain a negative price because of a data-entry mistake or a special adjustment.

**Business Example**

Impossible values can distort average prices, inventory summaries, and sales reports.

**AI/ML Use Case**

Valid-range checks help ensure that features supplied to a model follow the expected business rules.

**Importance in Data Analysis**

This assessment identifies values that may violate logical or business constraints before further processing.

In [11]:
# Check whether Quantity and Price are numeric
for column in ["Quantity", "Price"]:
    if column in df.columns:
        print(f"\nChecking {column}")

        numeric_values = pd.to_numeric(df[column], errors="coerce")

        print("Missing or Non-Numeric Values:",
              numeric_values.isna().sum())

        if column == "Quantity":
            # Zero quantities require investigation
            zero_quantity = df[numeric_values == 0]

            print("Zero Quantity Records:", len(zero_quantity))
            display(zero_quantity.head(10))

        elif column == "Price":
            # Negative prices require business-context checks
            negative_prices = df[numeric_values < 0]

            print("Negative Price Records:", len(negative_prices))
            display(negative_prices.head(10))

Checking Quantity
Missing or Non-Numeric Values: 0
Zero Quantity Records: 0

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

Checking Price
Missing or Non-Numeric Values: 0
Negative Price Records: 3

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom

## Code Explanation

**1. `for column in ["Quantity", "Price"]:`**

Loops through the two numerical columns that we want to investigate.

**2. `if column in df.columns:`**

Checks whether each column exists before analysing it.

**3. `pd.to_numeric(df[column], errors="coerce")`**

Attempts to convert the selected column to numeric values.

- Valid numeric values remain numeric.
- Values that cannot be converted become `NaN` because `errors="coerce"` is used.

The original DataFrame is not modified by this assignment.

**4. `numeric_values.isna().sum()`**

Counts missing values and values that became `NaN` during numeric conversion. This helps reveal whether a column contains non-numeric entries.

**5. `numeric_values == 0`**

Creates a condition to identify zero quantities. The corresponding rows are selected for investigation.

**6. `numeric_values < 0`**

Identifies negative prices that may require investigation under the business rules.

**7. `len()` and `display()`**

`len()` counts the selected records, while `display()` shows up to ten examples.

**What does the output mean?**

The output helps identify zero-quantity records, negative-price records, and values that are missing or cannot be interpreted numerically.

These checks do not prove that every flagged record is invalid. They identify records that need further investigation.

**Important Note**

A zero quantity may reflect a special transaction or data issue. A negative price may have a business explanation. Always confirm the intended rules before changing records.

**Impact on the ML Pipeline**

Impossible-value checks support reliable data validation before feature engineering and model training. Documented business rules should determine how confirmed invalid values are handled.

# Topic 11: Incorrect Categories

## Step 1: Understand the Concept

Incorrect categories are categorical values that do not follow the expected naming or classification rules of a dataset.

They may occur because of spelling mistakes, inconsistent capitalization, leading or trailing spaces, abbreviations, or incorrect labels.

**Examples**

- `"United Kingdom"` and `"United kingdom"`
- `"Chennai"` and `" Chennai"`
- `"Electronics"` and `"Electronic"` when both are intended to represent the same category

**Why do we check incorrect categories?**

- To identify inconsistent category labels.
- To avoid counting the same category separately.
- To improve the accuracy of grouping and summarization.
- To prepare consistent categorical features for machine learning.

**Important:** Different category values are not necessarily incorrect. Some may represent genuinely different categories, so corrections should follow verified business rules.

## Step 2: Demonstrate the Concept

**Simple Example**

| Customer City |
|---|
| Chennai |
| chennai |
| Chennai |
| Chennai |

The values may refer to the same city, but capitalization makes them appear different.

**Real-World Example**

In retail data, country names may contain spelling variations or unnecessary spaces.

**Business Example**

Inconsistent country names can split sales totals across multiple groups and make country-level reports misleading.

**AI/ML Use Case**

Inconsistent categories can create unnecessary feature values when categorical data is encoded for machine learning.

**Importance in Data Analysis**

Checking category consistency helps ensure that grouping, counting, and comparisons use meaningful category labels.

In [12]:
# Inspect unique values in the Country column
if "Country" in df.columns:
    print("Number of Unique Country Values:",
          df["Country"].nunique(dropna=True))

    print("\nCountry Values:")
    display(
        df["Country"]
        .value_counts(dropna=False)
        .to_frame(name="Record Count")
    )

    # Identify values with leading or trailing spaces
    country_text = df["Country"].astype("string")

    whitespace_mask = (
        country_text.notna()
        & country_text.ne(country_text.str.strip())
    )

    print("\nCountry Values with Extra Outer Spaces:",
          whitespace_mask.sum())

    display(df.loc[whitespace_mask, ["Country"]].head(10))
else:
    print("Country column is not available.")

Number of Unique Country Values: 40

Country Values:

                      Record Count
Country
United Kingdom              485852
EIRE                          9670
Germany                       8129
France                        5772
Netherlands                   2769
Spain                         1278
Switzerland                   1187
Portugal                      1101
Belgium                       1054
Channel Islands                906
Sweden                         902
Italy                          731
Australia                      654
Cyprus                         554
Austria                        537
Greece                         517
United Arab Emirates           432
Denmark                        428
Norway                         369
Finland                        354
Unspecified                    310
USA                            244
Japan                          224
Poland                         194
Malta                          172
Lithuania                      154
Singapore                      117
RSA                            111
Bahrain                        107
Canada                          77
Hong Kong                       76
Thailand                        76
Israel                          74
Iceland                         71
Korea                           63
Brazil                          62
West Indies                     54
Bermuda                         34
Nigeria                         32
Lebanon                         13

Country Values with Extra Outer Spaces: 0

Empty DataFrame
Columns: [Country]
Index: []

## Code Explanation

**1. `if "Country" in df.columns:`**

Checks whether the Country column exists before running the analysis.

**2. `df["Country"].nunique(dropna=True)`**

Counts the distinct non-missing country values.

- `nunique()` counts unique values.
- `dropna=True` excludes missing values from the count.

**3. `value_counts(dropna=False)`**

Counts how often each country value occurs. Setting `dropna=False` also includes missing values in the summary.

**4. `.to_frame(name="Record Count")`**

Converts the frequency results into a DataFrame with a descriptive column name.

**5. `astype("string")`**

Creates a string representation of the Country column for text inspection. It does not modify the original column.

**6. `country_text.notna()`**

Selects non-missing country values so that missing values are not treated as whitespace problems.

**7. `country_text.ne(country_text.str.strip())`**

Compares each value with a version that has leading and trailing whitespace removed.

- `str.strip()` removes whitespace from the beginning and end.
- `ne()` checks whether the original value differs from the stripped value.

If they differ, the value contains unnecessary outer whitespace.

**8. `whitespace_mask.sum()` and `display()`**

Counts records with extra outer spaces and displays up to ten examples.

**What does the output mean?**

The unique-value count and frequency table show the country labels present in the dataset. The whitespace check identifies records that may have inconsistent formatting.

This code does not automatically correct spelling or capitalization. Those changes require confirmation that the labels refer to the same category.

**Impact on the ML Pipeline**

Consistent category labels help prevent duplicate categories during feature encoding and improve the reliability of grouped analysis.

# Topic 12: Invalid Dates

## Step 1: Understand the Concept

Invalid dates are date values that cannot be interpreted correctly or that violate the expected date rules of a dataset.

They may occur because of incorrect formatting, data-entry mistakes, missing values, or invalid date components.

**Examples**

- `2020-15-40`: invalid month and day.
- `not-a-date`: text that cannot be interpreted as a date.
- A missing invoice date where the date is required for transaction analysis.
- A date outside the permitted business period, if a verified rule defines that period.

**Why do we check invalid dates?**

- To identify records that cannot be used reliably in time-based analysis.
- To prevent errors when sorting or grouping transactions by date.
- To support accurate monthly and yearly summaries.
- To prepare valid date features for machine learning.

**Important:** A date that is old or unexpected is not automatically invalid. Validation rules should reflect the dataset's source and business requirements.

## Step 2: Demonstrate the Concept

**Simple Example**

| InvoiceDate |
|---|
| 2010-01-05 |
| 2010-03-12 |
| not-a-date |
| Missing |

The first two entries are valid date examples. The third is unparseable text, and the fourth represents missing information if it is stored as a null value.

**Real-World Example**

An online retail system may store a transaction date in an unexpected format or contain a date-entry error.

**Business Example**

Incorrect invoice dates can cause transactions to appear in the wrong reporting month.

**AI/ML Use Case**

Valid dates are important when creating time-based features such as month, weekday, or time since a previous transaction.

**Importance in Data Analysis**

Date validation helps ensure that time-based summaries and calculations use reliable values.

In [13]:
# Check whether the InvoiceDate column exists
if "InvoiceDate" in df.columns:

    # Convert values for validation without changing the original column
    parsed_dates = pd.to_datetime(
        df["InvoiceDate"],
        errors="coerce"
    )

    # Identify missing values in the original date column
    missing_dates = df["InvoiceDate"].isna()

    # Identify non-missing values that could not be parsed
    invalid_date_mask = (
        df["InvoiceDate"].notna()
        & parsed_dates.isna()
    )

    print("Missing Invoice Dates:", missing_dates.sum())
    print("Unparseable Invoice Dates:", invalid_date_mask.sum())

    print("\nExamples of Unparseable Dates:")
    display(df.loc[invalid_date_mask, ["InvoiceDate"]].head(10))

else:
    print("InvoiceDate column is not available.")

Missing Invoice Dates: 0
Unparseable Invoice Dates: 0

Examples of Unparseable Dates:

Empty DataFrame
Columns: [InvoiceDate]
Index: []

## Code Explanation

**1. `if "InvoiceDate" in df.columns:`**

Checks whether the expected date column exists.

**2. `pd.to_datetime(df["InvoiceDate"], errors="coerce")`**

Attempts to interpret the values as dates.

- Valid date values are converted to pandas datetime values.
- Values that cannot be parsed become `NaT` because `errors="coerce"` is used.

The result is stored in `parsed_dates`; the original DataFrame column is not changed.

**3. `df["InvoiceDate"].isna()`**

Identifies values that were already missing in the original column.

**4. `df["InvoiceDate"].notna() & parsed_dates.isna()`**

Identifies values that were present originally but could not be parsed as dates.

Both conditions must be true:

- The original value is not missing.
- The parsed value is missing because conversion failed.

**5. `.sum()`**

Counts the missing and unparseable date values separately.

**6. `df.loc[invalid_date_mask, ["InvoiceDate"]]`**

Selects the original date values that could not be parsed, allowing us to inspect examples.

**7. `.head(10)` and `display()`**

Displays up to ten examples of unparseable dates.

**What does the output mean?**

- **Missing Invoice Dates** counts values that were already missing.
- **Unparseable Invoice Dates** counts non-missing values that could not be interpreted as dates.

If both counts are zero, pandas did not detect missing or unparseable values using these checks.

**Important Note**

This code checks whether values can be parsed as dates. It does not determine whether a valid date is historically or commercially appropriate. Also, ambiguous date formats may require an explicit format rule to ensure correct interpretation.

**Impact on the ML Pipeline**

Date validation helps prevent incorrect time-based features and unreliable time-series analysis. Any corrections should follow verified date-format and business rules.

# Topic 13: Incorrect Data Types

## Step 1: Understand the Concept

Incorrect data types occur when a column is stored using a data type that does not match its intended meaning or required operations.

Pandas supports data types such as integers, floating-point numbers, strings, Boolean values, and datetime values.

**Examples**

- Quantity stored as text instead of numeric data.
- Price stored as text instead of numeric data.
- InvoiceDate stored as text instead of datetime data.
- Numeric-looking customer identifiers treated as measurements rather than identifiers.

**Why do we check data types?**

- To ensure that calculations work correctly.
- To identify values that cannot be converted to the expected type.
- To support accurate filtering, grouping, and date operations.
- To prepare reliable features for data analysis and machine learning.

**Important:** A column's storage type and business meaning are not always the same. For example, Customer ID may be stored as a number but should usually be treated as an identifier, not a numerical measurement.

## Step 2: Demonstrate the Concept

**Simple Example**

| Quantity | Price | InvoiceDate |
|---|---|---|
| `"5"` | `"10.5"` | `"2010-01-05"` |
| `"3"` | `"20.0"` | `"2010-01-06"` |

If these values are stored as text, arithmetic and date operations may not behave as expected.

**Real-World Example**

An Excel file may contain prices or quantities formatted as text because of inconsistent data entry.

**Business Example**

Incorrect types can cause errors when calculating totals or preparing monthly sales reports.

**AI/ML Use Case**

Machine learning preprocessing requires features to be represented in suitable formats before transformations and model training.

**Importance in Data Analysis**

Checking data types helps identify conversion requirements before performing calculations or building features.

In [14]:
# Display the current data types
print("Current Data Types:")
display(df.dtypes.to_frame(name="Data Type"))

# Define columns expected to be numeric
expected_numeric_columns = ["Quantity", "Price"]

for column in expected_numeric_columns:
    if column in df.columns:
        converted_values = pd.to_numeric(
            df[column],
            errors="coerce"
        )

        invalid_numeric_mask = (
            df[column].notna()
            & converted_values.isna()
        )

        print(
            f"\n{column} - Values That Cannot Be Converted:",
            invalid_numeric_mask.sum()
        )

# Check the InvoiceDate data type
if "InvoiceDate" in df.columns:
    print("\nInvoiceDate Data Type:", df["InvoiceDate"].dtype)

    if not pd.api.types.is_datetime64_any_dtype(df["InvoiceDate"]):
        print("InvoiceDate may need datetime conversion.")
    else:
        print("InvoiceDate is stored as a datetime type.")

Current Data Types:

                  Data Type
Invoice              object
StockCode            object
Description          object
Quantity              int64
InvoiceDate  datetime64[us]
Price               float64
Customer ID         float64
Country                 str

Quantity - Values That Cannot Be Converted: 0

Price - Values That Cannot Be Converted: 0

InvoiceDate Data Type: datetime64[us]
InvoiceDate is stored as a datetime type.

## Code Explanation

**1. `df.dtypes`**

Returns the storage data type of each column, such as `int64`, `float64`, `object`, or a datetime type.

**2. `.to_frame(name="Data Type")`**

Converts the data-type information into a DataFrame for easier display.

**3. `expected_numeric_columns = ["Quantity", "Price"]`**

Defines the columns that are expected to contain numerical values for this dataset.

**4. `pd.to_numeric(df[column], errors="coerce")`**

Attempts to convert the selected column to numeric values. Values that cannot be converted become `NaN` in the temporary result.

**5. `df[column].notna() & converted_values.isna()`**

Identifies values that were originally present but could not be converted into numbers.

**6. `invalid_numeric_mask.sum()`**

Counts the non-missing values that failed numeric conversion.

**7. `df["InvoiceDate"].dtype`**

Displays the current storage type of the invoice date column.

**8. `pd.api.types.is_datetime64_any_dtype()`**

Checks whether the column uses a pandas datetime data type.

If it does not, the code prints a message suggesting that conversion may be needed. It does not convert the column automatically.

**What does the output mean?**

The first table shows the current storage type of each column. The numeric checks identify values that cannot be converted to numbers, and the date check indicates whether InvoiceDate is stored as datetime.

A column using `object` is not necessarily incorrect; it may contain valid text or identifiers. Always consider the intended meaning of the column.

**Impact on the ML Pipeline**

Correct data types support reliable feature engineering, numerical calculations, date transformations, and model preprocessing. This code only inspects and tests conversions; it does not change the original DataFrame.

# Topic 14: Unexpected Values

## Step 1: Understand the Concept

Unexpected values are values that differ from expected patterns, reasonable ranges, or established business rules.

Unlike impossible values, unexpected values may still be valid. They simply require further investigation to understand whether they represent genuine business activity or possible data-quality issues.

**Examples**

- An unusually large quantity in a retail transaction.
- A product price that is much higher than most other prices.
- An unexpected country label.
- An invoice date outside the expected reporting period.

**Why do we check unexpected values?**

- To identify unusual observations.
- To investigate possible data-entry or processing errors.
- To understand exceptional business events.
- To improve the reliability of data analysis.

**Important:** Do not remove unusual values simply because they are far from the average. They may represent genuine bulk orders, premium products, returns, or other important business events.

## Step 2: Demonstrate the Concept

**Simple Example**

| Product | Quantity | Price |
|---|---:|---:|
| Pen | 5 | 10 |
| Book | 2 | 50 |
| Chair | 5000 | 100 |

The quantity of 5000 is much larger than the other quantities. It is an unexpected value in this small example, but it could represent a genuine bulk order.

**Real-World Example**

An online retailer may receive an order for thousands of units from a business customer.

**Business Example**

Investigating unusually high quantities and prices helps businesses verify large orders and identify potential recording errors.

**AI/ML Use Case**

Unexpected values can influence statistical summaries and model behaviour. Analysts should investigate them before deciding whether a transformation or special treatment is appropriate.

**Importance in Data Analysis**

Unexpected-value checks help us understand unusual patterns and make informed decisions without automatically discarding useful data.

In [15]:
# Define numerical columns to inspect
numeric_columns = ["Quantity", "Price"]

for column in numeric_columns:
    if column in df.columns:
        print(f"\nUnexpected Value Summary for {column}:")

        # Calculate descriptive statistics
        display(df[column].describe().to_frame(name="Statistics"))

        # Calculate the 1.5 IQR bounds
        q1 = df[column].quantile(0.25)
        q3 = df[column].quantile(0.75)
        iqr = q3 - q1

        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr

        # Identify values outside the IQR bounds
        unusual_mask = (
            (df[column] < lower_bound)
            | (df[column] > upper_bound)
        )

        unusual_values = df.loc[unusual_mask]

        print("Lower Bound:", lower_bound)
        print("Upper Bound:", upper_bound)
        print("Number of Unusual Records:", len(unusual_values))

        display(unusual_values.head(10))

Unexpected Value Summary for Quantity:

          Statistics
count  525461.000000
mean       10.337667
std       107.424110
min     -9600.000000
25%         1.000000
50%         3.000000
75%        10.000000
max     19152.000000

Lower Bound: -12.5
Upper Bound: 23.5
Number of Unusual Records: 57870

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
10,489435,22195,HEART MEASURING SPOONS LARGE,24,2009-12-01 07:46:00,1.65,13085.0,United Kingdom
30,489436,22111,SCOTTIE DOG HOT WATER BOTTLE,24,2009-12-01 09:06:00,4.25,13078.0,United Kingdom
54,489438,21329,DINOSAURS WRITING SET,28,2009-12-01 09:24:00,0.98,18102.0,United Kingdom
55,489438,21252,SET OF MEADOW FLOWER STICKERS,30,2009-12-01 09:24:00,1.69,18102.0,United Kingdom
56,489438,21100,CHARLIE AND LOLA CHARLOTTE BAG,30,2009-12-01 09:24:00,1.15,18102.0,United Kingdom
57,489438,21033,JUMBO BAG CHARLIE AND LOLA TOYS,30,2009-12-01 09:24:00,2.00,18102.0,United Kingdom

Unexpected Value Summary for Price:

          Statistics
count  525461.000000
mean        4.688834
std       146.126914
min    -53594.360000
25%         1.250000
50%         2.100000
75%         4.210000
max     25111.090000

Lower Bound: -3.1899999999999995
Upper Bound: 8.649999999999999
Number of Unusual Records: 35273

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
35,489437,21360,JOY LARGE WOOD LETTERS,1,2009-12-01 09:08:00,9.95,15362.0,United Kingdom
38,489437,35400,WOODEN BOX ADVENT CALENDAR,2,2009-12-01 09:08:00,8.95,15362.0,United Kingdom
89,489439,POST,POSTAGE,3,2009-12-01 09:28:00,18.00,12682.0,France
126,489444,POST,POSTAGE,1,2009-12-01 09:55:00,141.00,12636.0,USA
131,489445,22180,RETRO SPOT LAMP,2,2009-12-01 09:57:00,9.95,17519.0,United Kingdom
140,489445,21299,EDWARDIAN TOILET ROLL UNIT,1,2009-12-01 09:57:00,12.75,17519.0,United Kingdom
170,489446,21217,RED SPOTTY ROUND CAKE TINS,12,2009-12-01 10:06:00,8.95,13758.0,United Kingdom
172,489446,85066,CREAM SWEETHEART MINI CHEST,2,2009-12-01 10:06:00,12.75,13758.0,United Kingdom
173,489447,POST,POSTAGE,1,2009-12-01 10:10:00,130.00,12362.0,Belgium
248,489461,22180,RETRO SPOT LAMP,2,2009-12-01 10:49:00,9.95,17865.0,United Kingdom

## Code Explanation

**1. `numeric_columns = ["Quantity", "Price"]`**

Selects the numerical columns to inspect for unusual values.

**2. `for column in numeric_columns:`**

Loops through each selected column so the same analysis can be applied to both Quantity and Price.

**3. `df[column].describe()`**

Calculates descriptive statistics, including count, mean, standard deviation, minimum, quartiles, and maximum. These statistics help us understand the distribution of values.

**4. `quantile(0.25)` and `quantile(0.75)`**

Calculate the first quartile (Q1) and third quartile (Q3).

- Q1 is the 25th percentile.
- Q3 is the 75th percentile.

**5. `iqr = q3 - q1`**

Calculates the interquartile range (IQR), which measures the spread of the middle 50% of the data.

**6. Calculate the lower and upper bounds**

The code uses the common 1.5 × IQR rule:

- Lower bound = Q1 − 1.5 × IQR
- Upper bound = Q3 + 1.5 × IQR

**7. `unusual_mask`**

Identifies values below the lower bound or above the upper bound.

**8. `df.loc[unusual_mask]`**

Selects the records flagged by the IQR rule.

**9. `len(unusual_values)` and `head(10)`**

Counts the flagged records and displays up to ten examples.

**What does the output mean?**

The descriptive statistics summarize the values in each column. The IQR bounds provide a statistical rule for flagging unusually low or high values.

A flagged value is a potential outlier, not proof of an error. For example, a very large Quantity could be a legitimate bulk order.

**Important Note**

The IQR rule is a general statistical method, not a business rule. Its results depend on the distribution of the data. Investigate flagged records before correcting, removing, or transforming them.

**Impact on the ML Pipeline**

Unexpected-value analysis helps assess potential outliers before feature engineering and model training. Any treatment should depend on the business meaning, data distribution, and modelling objective.

# Topic 15: Empty Strings

## Step 1: Understand the Concept

An empty string is a text value that contains no characters. A whitespace-only string contains spaces but no meaningful text.

Examples include:

- `""` — an empty string.
- `"   "` — a string containing only spaces.
- `"Chennai"` — a non-empty string.

Empty strings and whitespace-only strings are different from standard missing values such as `NaN` or `None`.

**Why do we check empty strings?**

- To identify incomplete text fields.
- To distinguish blank text from standard missing values.
- To improve the quality of categorical data.
- To prevent blank values from being treated as meaningful categories during analysis or machine learning.

**Important:** An empty string may represent missing information, but the correct treatment depends on the meaning of the column.

## Step 2: Demonstrate the Concept

**Simple Example**

| Customer | City |
|---|---|
| Arun | Chennai |
| Priya | `""` |
| Ravi | `"   "` |
| Meena | Madurai |

Priya's City value is an empty string, while Ravi's City value contains spaces only.

**Real-World Example**

A data-entry form may allow a transaction to be saved without entering a product description.

**Business Example**

Blank product descriptions can make product reports difficult to interpret and may affect product-level summaries.

**AI/ML Use Case**

Empty strings may be treated as a separate category during encoding, even when they actually represent missing information.

**Importance in Data Analysis**

Checking empty strings helps detect incomplete text fields that a standard missing-value check may not identify.

In [16]:
# Identify text-like columns
text_columns = df.select_dtypes(
    include=["object", "string", "category"]
).columns

empty_string_counts = {}

for column in text_columns:
    text_values = df[column].astype("string")

    # Detect empty strings and whitespace-only strings
    empty_mask = (
        text_values.notna()
        & text_values.str.strip().eq("")
    )

    empty_string_counts[column] = empty_mask.sum()

# Display counts for each text-like column
empty_string_summary = pd.Series(
    empty_string_counts,
    name="Empty or Whitespace-Only Count"
)

print("Empty Strings by Text Column:")
display(empty_string_summary.to_frame())

print(
    "\nTotal Empty or Whitespace-Only Values:",
    int(empty_string_summary.sum())
)

Empty Strings by Text Column:

             Empty or Whitespace-Only Count
Invoice                                   0
StockCode                                 0
Description                               0
Country                                   0

Total Empty or Whitespace-Only Values: 0

## Code Explanation

**1. `df.select_dtypes(include=["object", "string", "category"])`**

Selects columns stored as object, string, or category data types. These are the columns most likely to contain text values.

**2. `.columns`**

Returns the names of the selected columns.

**3. `empty_string_counts = {}`**

Creates an empty dictionary to store the number of empty or whitespace-only values in each text column.

**4. `df[column].astype("string")`**

Creates a string-typed version of the column for inspection. The original DataFrame is not changed.

**5. `text_values.notna()`**

Excludes standard missing values from the empty-string check.

**6. `text_values.str.strip().eq("")`**

- `str.strip()` removes whitespace from the beginning and end of each string.
- `eq("")` checks whether the resulting string is empty.

This identifies both zero-length strings and strings containing only whitespace.

**7. `empty_mask.sum()`**

Counts how many records in the selected column match the empty-string condition.

**8. `pd.Series(empty_string_counts, name="Empty or Whitespace-Only Count")`**

Converts the dictionary into a pandas Series with a descriptive name.

**9. `.to_frame()` and `display()`**

Convert and display the summary in a notebook-friendly table.

**10. `empty_string_summary.sum()`**

Adds the counts across text columns to calculate the total number of empty or whitespace-only cells detected. Each cell belongs to one column, so these counts can be added together.

**What does the output mean?**

The summary shows which text columns contain empty or whitespace-only values and how many are present in each column.

A count of zero means no empty or whitespace-only strings were detected in the selected text-like columns.

**Important Note**

This check does not count standard null values as empty strings. It also does not modify the original dataset.

**Impact on the ML Pipeline**

Detecting blank text values helps prevent accidental blank categories and supports consistent handling of incomplete categorical features.

# Topic 16: Null-Like Values

## Step 1: Understand the Concept

Null-like values are text values that may be used to represent missing or unavailable information.

Common examples include:

- `"NULL"`
- `"None"`
- `"N/A"`
- `"NA"`
- `"unknown"`
- `"not available"`

These values are stored as ordinary text strings, so pandas may not recognize them as standard missing values such as `NaN` or `None`.

**Why do we check null-like values?**

- To identify missing information represented as text.
- To improve data consistency.
- To prevent incorrect categories during analysis.
- To prepare reliable data for machine learning.

**Important:** A null-like text value should only be treated as missing after checking the meaning of the column and the dataset's rules.

## Step 2: Demonstrate the Concept

**Simple Example**

| Customer | City |
|---|---|
| Arun | Chennai |
| Priya | N/A |
| Ravi | Unknown |
| Meena | Madurai |

The values `"N/A"` and `"Unknown"` may indicate that the city information is unavailable.

**Real-World Example**

A registration form may save `"N/A"` when a customer does not provide an optional field.

**Business Example**

If unavailable product information is stored as `"NULL"`, a report may incorrectly count it as a valid product category.

**AI/ML Use Case**

Null-like values can create misleading categories when categorical features are encoded for machine learning models.

**Importance in Data Analysis**

Identifying these values helps distinguish genuine information from text that may represent missing data.

In [17]:
# Define common text placeholders that may represent missing values
null_like_values = [
    "NULL",
    "None",
    "N/A",
    "NA",
    "N.A.",
    "not available",
    "unknown"
]

# Select text-like columns
text_columns = df.select_dtypes(
    include=["object", "string", "category"]
).columns

null_like_summary = {}

for column in text_columns:
    text_values = df[column].astype("string")

    # Normalize text for comparison without changing the original data
    normalized_values = text_values.str.strip().str.casefold()

    # Identify values matching the specified placeholders
    null_like_mask = normalized_values.isin(
        [value.casefold() for value in null_like_values]
    )

    null_like_summary[column] = int(null_like_mask.sum())

# Display counts by column
summary = pd.Series(
    null_like_summary,
    name="Null-Like Value Count"
)

print("Null-Like Values by Text Column:")
display(summary.to_frame())

print(
    "\nTotal Null-Like Values:",
    int(summary.sum())
)

Null-Like Values by Text Column:

             Null-Like Value Count
Invoice                          0
StockCode                        0
Description                      0
Country                          0

Total Null-Like Values: 0

## Code Explanation

**1. `null_like_values`**

Creates a list of common text placeholders that may represent missing information.

**2. `df.select_dtypes(include=["object", "string", "category"])`**

Selects columns that may contain text values.

**3. `df[column].astype("string")`**

Converts each selected column to pandas' string data type for checking. The original DataFrame remains unchanged.

**4. `.str.strip()`**

Removes spaces from the beginning and end of text values. For example, `" NULL "` becomes `"NULL"` for comparison.

**5. `.str.casefold()`**

Makes text comparison case-insensitive. For example, `"NULL"`, `"null"`, and `"Null"` are treated as equivalent.

**6. `.isin()`**

Checks whether each value matches one of the specified null-like placeholders.

**7. `null_like_mask.sum()`**

Counts the matching values in each column.

**8. `pd.Series(null_like_summary, name="Null-Like Value Count")`**

Creates a summary containing the number of detected null-like values in each text column.

**9. `display(summary.to_frame())`**

Displays the summary as a table in Jupyter Notebook.

**10. `summary.sum()`**

Calculates the total number of matching cells across the selected columns.

**What does the output mean?**

- A positive count indicates that the column contains one or more specified placeholders.
- A count of zero indicates that none of the listed placeholders were detected in that column.
- The total shows the number of matching cells across all selected text columns.

**Important Note**

The result depends on the placeholders included in `null_like_values`. Other spellings or placeholders will not be detected unless they are added to the list. Some values, such as `"unknown"`, may be meaningful in certain datasets, so verify them before replacing anything.

**Impact on the ML Pipeline**

Checking null-like values helps standardize missing-data handling before feature engineering, encoding, and model training. This code only identifies values; it does not replace or delete them.